package com.viaversion.viaversion.protocols.protocol1_12_1to1_12;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ClientboundPackets1_12_1 implements ClientboundPacketType
{
    SPAWN_ENTITY("SPAWN_ENTITY", 0), 
    SPAWN_EXPERIENCE_ORB("SPAWN_EXPERIENCE_ORB", 1), 
    SPAWN_GLOBAL_ENTITY("SPAWN_GLOBAL_ENTITY", 2), 
    SPAWN_MOB("SPAWN_MOB", 3), 
    SPAWN_PAINTING("SPAWN_PAINTING", 4), 
    SPAWN_PLAYER("SPAWN_PLAYER", 5), 
    ENTITY_ANIMATION("ENTITY_ANIMATION", 6), 
    STATISTICS("STATISTICS", 7), 
    BLOCK_BREAK_ANIMATION("BLOCK_BREAK_ANIMATION", 8), 
    BLOCK_ENTITY_DATA("BLOCK_ENTITY_DATA", 9), 
    BLOCK_ACTION("BLOCK_ACTION", 10), 
    BLOCK_CHANGE("BLOCK_CHANGE", 11), 
    BOSSBAR("BOSSBAR", 12), 
    SERVER_DIFFICULTY("SERVER_DIFFICULTY", 13), 
    TAB_COMPLETE("TAB_COMPLETE", 14), 
    CHAT_MESSAGE("CHAT_MESSAGE", 15), 
    MULTI_BLOCK_CHANGE("MULTI_BLOCK_CHANGE", 16), 
    WINDOW_CONFIRMATION("WINDOW_CONFIRMATION", 17), 
    CLOSE_WINDOW("CLOSE_WINDOW", 18), 
    OPEN_WINDOW("OPEN_WINDOW", 19), 
    WINDOW_ITEMS("WINDOW_ITEMS", 20), 
    WINDOW_PROPERTY("WINDOW_PROPERTY", 21), 
    SET_SLOT("SET_SLOT", 22), 
    COOLDOWN("COOLDOWN", 23), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 24), 
    NAMED_SOUND("NAMED_SOUND", 25), 
    DISCONNECT("DISCONNECT", 26), 
    ENTITY_STATUS("ENTITY_STATUS", 27), 
    EXPLOSION("EXPLOSION", 28), 
    UNLOAD_CHUNK("UNLOAD_CHUNK", 29), 
    GAME_EVENT("GAME_EVENT", 30), 
    KEEP_ALIVE("KEEP_ALIVE", 31), 
    CHUNK_DATA("CHUNK_DATA", 32), 
    EFFECT("EFFECT", 33), 
    SPAWN_PARTICLE("SPAWN_PARTICLE", 34), 
    JOIN_GAME("JOIN_GAME", 35), 
    MAP_DATA("MAP_DATA", 36), 
    ENTITY_MOVEMENT("ENTITY_MOVEMENT", 37), 
    ENTITY_POSITION("ENTITY_POSITION", 38), 
    ENTITY_POSITION_AND_ROTATION("ENTITY_POSITION_AND_ROTATION", 39), 
    ENTITY_ROTATION("ENTITY_ROTATION", 40), 
    VEHICLE_MOVE("VEHICLE_MOVE", 41), 
    OPEN_SIGN_EDITOR("OPEN_SIGN_EDITOR", 42), 
    CRAFT_RECIPE_RESPONSE("CRAFT_RECIPE_RESPONSE", 43), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 44), 
    COMBAT_EVENT("COMBAT_EVENT", 45), 
    PLAYER_INFO("PLAYER_INFO", 46), 
    PLAYER_POSITION("PLAYER_POSITION", 47), 
    USE_BED("USE_BED", 48), 
    UNLOCK_RECIPES("UNLOCK_RECIPES", 49), 
    DESTROY_ENTITIES("DESTROY_ENTITIES", 50), 
    REMOVE_ENTITY_EFFECT("REMOVE_ENTITY_EFFECT", 51), 
    RESOURCE_PACK("RESOURCE_PACK", 52), 
    RESPAWN("RESPAWN", 53), 
    ENTITY_HEAD_LOOK("ENTITY_HEAD_LOOK", 54), 
    SELECT_ADVANCEMENTS_TAB("SELECT_ADVANCEMENTS_TAB", 55), 
    WORLD_BORDER("WORLD_BORDER", 56), 
    CAMERA("CAMERA", 57), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 58), 
    DISPLAY_SCOREBOARD("DISPLAY_SCOREBOARD", 59), 
    ENTITY_METADATA("ENTITY_METADATA", 60), 
    ATTACH_ENTITY("ATTACH_ENTITY", 61), 
    ENTITY_VELOCITY("ENTITY_VELOCITY", 62), 
    ENTITY_EQUIPMENT("ENTITY_EQUIPMENT", 63), 
    SET_EXPERIENCE("SET_EXPERIENCE", 64), 
    UPDATE_HEALTH("UPDATE_HEALTH", 65), 
    SCOREBOARD_OBJECTIVE("SCOREBOARD_OBJECTIVE", 66), 
    SET_PASSENGERS("SET_PASSENGERS", 67), 
    TEAMS("TEAMS", 68), 
    UPDATE_SCORE("UPDATE_SCORE", 69), 
    SPAWN_POSITION("SPAWN_POSITION", 70), 
    TIME_UPDATE("TIME_UPDATE", 71), 
    TITLE("TITLE", 72), 
    SOUND("SOUND", 73), 
    TAB_LIST("TAB_LIST", 74), 
    COLLECT_ITEM("COLLECT_ITEM", 75), 
    ENTITY_TELEPORT("ENTITY_TELEPORT", 76), 
    ADVANCEMENTS("ADVANCEMENTS", 77), 
    ENTITY_PROPERTIES("ENTITY_PROPERTIES", 78), 
    ENTITY_EFFECT("ENTITY_EFFECT", 79);
    
    private static final ClientboundPackets1_12_1[] $VALUES;
    
    private ClientboundPackets1_12_1(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ClientboundPackets1_12_1[] { ClientboundPackets1_12_1.SPAWN_ENTITY, ClientboundPackets1_12_1.SPAWN_EXPERIENCE_ORB, ClientboundPackets1_12_1.SPAWN_GLOBAL_ENTITY, ClientboundPackets1_12_1.SPAWN_MOB, ClientboundPackets1_12_1.SPAWN_PAINTING, ClientboundPackets1_12_1.SPAWN_PLAYER, ClientboundPackets1_12_1.ENTITY_ANIMATION, ClientboundPackets1_12_1.STATISTICS, ClientboundPackets1_12_1.BLOCK_BREAK_ANIMATION, ClientboundPackets1_12_1.BLOCK_ENTITY_DATA, ClientboundPackets1_12_1.BLOCK_ACTION, ClientboundPackets1_12_1.BLOCK_CHANGE, ClientboundPackets1_12_1.BOSSBAR, ClientboundPackets1_12_1.SERVER_DIFFICULTY, ClientboundPackets1_12_1.TAB_COMPLETE, ClientboundPackets1_12_1.CHAT_MESSAGE, ClientboundPackets1_12_1.MULTI_BLOCK_CHANGE, ClientboundPackets1_12_1.WINDOW_CONFIRMATION, ClientboundPackets1_12_1.CLOSE_WINDOW, ClientboundPackets1_12_1.OPEN_WINDOW, ClientboundPackets1_12_1.WINDOW_ITEMS, ClientboundPackets1_12_1.WINDOW_PROPERTY, ClientboundPackets1_12_1.SET_SLOT, ClientboundPackets1_12_1.COOLDOWN, ClientboundPackets1_12_1.PLUGIN_MESSAGE, ClientboundPackets1_12_1.NAMED_SOUND, ClientboundPackets1_12_1.DISCONNECT, ClientboundPackets1_12_1.ENTITY_STATUS, ClientboundPackets1_12_1.EXPLOSION, ClientboundPackets1_12_1.UNLOAD_CHUNK, ClientboundPackets1_12_1.GAME_EVENT, ClientboundPackets1_12_1.KEEP_ALIVE, ClientboundPackets1_12_1.CHUNK_DATA, ClientboundPackets1_12_1.EFFECT, ClientboundPackets1_12_1.SPAWN_PARTICLE, ClientboundPackets1_12_1.JOIN_GAME, ClientboundPackets1_12_1.MAP_DATA, ClientboundPackets1_12_1.ENTITY_MOVEMENT, ClientboundPackets1_12_1.ENTITY_POSITION, ClientboundPackets1_12_1.ENTITY_POSITION_AND_ROTATION, ClientboundPackets1_12_1.ENTITY_ROTATION, ClientboundPackets1_12_1.VEHICLE_MOVE, ClientboundPackets1_12_1.OPEN_SIGN_EDITOR, ClientboundPackets1_12_1.CRAFT_RECIPE_RESPONSE, ClientboundPackets1_12_1.PLAYER_ABILITIES, ClientboundPackets1_12_1.COMBAT_EVENT, ClientboundPackets1_12_1.PLAYER_INFO, ClientboundPackets1_12_1.PLAYER_POSITION, ClientboundPackets1_12_1.USE_BED, ClientboundPackets1_12_1.UNLOCK_RECIPES, ClientboundPackets1_12_1.DESTROY_ENTITIES, ClientboundPackets1_12_1.REMOVE_ENTITY_EFFECT, ClientboundPackets1_12_1.RESOURCE_PACK, ClientboundPackets1_12_1.RESPAWN, ClientboundPackets1_12_1.ENTITY_HEAD_LOOK, ClientboundPackets1_12_1.SELECT_ADVANCEMENTS_TAB, ClientboundPackets1_12_1.WORLD_BORDER, ClientboundPackets1_12_1.CAMERA, ClientboundPackets1_12_1.HELD_ITEM_CHANGE, ClientboundPackets1_12_1.DISPLAY_SCOREBOARD, ClientboundPackets1_12_1.ENTITY_METADATA, ClientboundPackets1_12_1.ATTACH_ENTITY, ClientboundPackets1_12_1.ENTITY_VELOCITY, ClientboundPackets1_12_1.ENTITY_EQUIPMENT, ClientboundPackets1_12_1.SET_EXPERIENCE, ClientboundPackets1_12_1.UPDATE_HEALTH, ClientboundPackets1_12_1.SCOREBOARD_OBJECTIVE, ClientboundPackets1_12_1.SET_PASSENGERS, ClientboundPackets1_12_1.TEAMS, ClientboundPackets1_12_1.UPDATE_SCORE, ClientboundPackets1_12_1.SPAWN_POSITION, ClientboundPackets1_12_1.TIME_UPDATE, ClientboundPackets1_12_1.TITLE, ClientboundPackets1_12_1.SOUND, ClientboundPackets1_12_1.TAB_LIST, ClientboundPackets1_12_1.COLLECT_ITEM, ClientboundPackets1_12_1.ENTITY_TELEPORT, ClientboundPackets1_12_1.ADVANCEMENTS, ClientboundPackets1_12_1.ENTITY_PROPERTIES, ClientboundPackets1_12_1.ENTITY_EFFECT };
    }
}
