package com.viaversion.viaversion.protocols.protocol1_14to1_13_2;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ClientboundPackets1_14 implements ClientboundPacketType
{
    SPAWN_ENTITY("SPAWN_ENTITY", 0), 
    SPAWN_EXPERIENCE_ORB("SPAWN_EXPERIENCE_ORB", 1), 
    SPAWN_GLOBAL_ENTITY("SPAWN_GLOBAL_ENTITY", 2), 
    SPAWN_MOB("SPAWN_MOB", 3), 
    SPAWN_PAINTING("SPAWN_PAINTING", 4), 
    SPAWN_PLAYER("SPAWN_PLAYER", 5), 
    ENTITY_ANIMATION("ENTITY_ANIMATION", 6), 
    STATISTICS("STATISTICS", 7), 
    BLOCK_BREAK_ANIMATION("BLOCK_BREAK_ANIMATION", 8), 
    BLOCK_ENTITY_DATA("BLOCK_ENTITY_DATA", 9), 
    BLOCK_ACTION("BLOCK_ACTION", 10), 
    BLOCK_CHANGE("BLOCK_CHANGE", 11), 
    BOSSBAR("BOSSBAR", 12), 
    SERVER_DIFFICULTY("SERVER_DIFFICULTY", 13), 
    CHAT_MESSAGE("CHAT_MESSAGE", 14), 
    MULTI_BLOCK_CHANGE("MULTI_BLOCK_CHANGE", 15), 
    TAB_COMPLETE("TAB_COMPLETE", 16), 
    DECLARE_COMMANDS("DECLARE_COMMANDS", 17), 
    WINDOW_CONFIRMATION("WINDOW_CONFIRMATION", 18), 
    CLOSE_WINDOW("CLOSE_WINDOW", 19), 
    WINDOW_ITEMS("WINDOW_ITEMS", 20), 
    WINDOW_PROPERTY("WINDOW_PROPERTY", 21), 
    SET_SLOT("SET_SLOT", 22), 
    COOLDOWN("COOLDOWN", 23), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 24), 
    NAMED_SOUND("NAMED_SOUND", 25), 
    DISCONNECT("DISCONNECT", 26), 
    ENTITY_STATUS("ENTITY_STATUS", 27), 
    EXPLOSION("EXPLOSION", 28), 
    UNLOAD_CHUNK("UNLOAD_CHUNK", 29), 
    GAME_EVENT("GAME_EVENT", 30), 
    OPEN_HORSE_WINDOW("OPEN_HORSE_WINDOW", 31), 
    KEEP_ALIVE("KEEP_ALIVE", 32), 
    CHUNK_DATA("CHUNK_DATA", 33), 
    EFFECT("EFFECT", 34), 
    SPAWN_PARTICLE("SPAWN_PARTICLE", 35), 
    UPDATE_LIGHT("UPDATE_LIGHT", 36), 
    JOIN_GAME("JOIN_GAME", 37), 
    MAP_DATA("MAP_DATA", 38), 
    TRADE_LIST("TRADE_LIST", 39), 
    ENTITY_POSITION("ENTITY_POSITION", 40), 
    ENTITY_POSITION_AND_ROTATION("ENTITY_POSITION_AND_ROTATION", 41), 
    ENTITY_ROTATION("ENTITY_ROTATION", 42), 
    ENTITY_MOVEMENT("ENTITY_MOVEMENT", 43), 
    VEHICLE_MOVE("VEHICLE_MOVE", 44), 
    OPEN_BOOK("OPEN_BOOK", 45), 
    OPEN_WINDOW("OPEN_WINDOW", 46), 
    OPEN_SIGN_EDITOR("OPEN_SIGN_EDITOR", 47), 
    CRAFT_RECIPE_RESPONSE("CRAFT_RECIPE_RESPONSE", 48), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 49), 
    COMBAT_EVENT("COMBAT_EVENT", 50), 
    PLAYER_INFO("PLAYER_INFO", 51), 
    FACE_PLAYER("FACE_PLAYER", 52), 
    PLAYER_POSITION("PLAYER_POSITION", 53), 
    UNLOCK_RECIPES("UNLOCK_RECIPES", 54), 
    DESTROY_ENTITIES("DESTROY_ENTITIES", 55), 
    REMOVE_ENTITY_EFFECT("REMOVE_ENTITY_EFFECT", 56), 
    RESOURCE_PACK("RESOURCE_PACK", 57), 
    RESPAWN("RESPAWN", 58), 
    ENTITY_HEAD_LOOK("ENTITY_HEAD_LOOK", 59), 
    SELECT_ADVANCEMENTS_TAB("SELECT_ADVANCEMENTS_TAB", 60), 
    WORLD_BORDER("WORLD_BORDER", 61), 
    CAMERA("CAMERA", 62), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 63), 
    UPDATE_VIEW_POSITION("UPDATE_VIEW_POSITION", 64), 
    UPDATE_VIEW_DISTANCE("UPDATE_VIEW_DISTANCE", 65), 
    DISPLAY_SCOREBOARD("DISPLAY_SCOREBOARD", 66), 
    ENTITY_METADATA("ENTITY_METADATA", 67), 
    ATTACH_ENTITY("ATTACH_ENTITY", 68), 
    ENTITY_VELOCITY("ENTITY_VELOCITY", 69), 
    ENTITY_EQUIPMENT("ENTITY_EQUIPMENT", 70), 
    SET_EXPERIENCE("SET_EXPERIENCE", 71), 
    UPDATE_HEALTH("UPDATE_HEALTH", 72), 
    SCOREBOARD_OBJECTIVE("SCOREBOARD_OBJECTIVE", 73), 
    SET_PASSENGERS("SET_PASSENGERS", 74), 
    TEAMS("TEAMS", 75), 
    UPDATE_SCORE("UPDATE_SCORE", 76), 
    SPAWN_POSITION("SPAWN_POSITION", 77), 
    TIME_UPDATE("TIME_UPDATE", 78), 
    TITLE("TITLE", 79), 
    ENTITY_SOUND("ENTITY_SOUND", 80), 
    SOUND("SOUND", 81), 
    STOP_SOUND("STOP_SOUND", 82), 
    TAB_LIST("TAB_LIST", 83), 
    NBT_QUERY("NBT_QUERY", 84), 
    COLLECT_ITEM("COLLECT_ITEM", 85), 
    ENTITY_TELEPORT("ENTITY_TELEPORT", 86), 
    ADVANCEMENTS("ADVANCEMENTS", 87), 
    ENTITY_PROPERTIES("ENTITY_PROPERTIES", 88), 
    ENTITY_EFFECT("ENTITY_EFFECT", 89), 
    DECLARE_RECIPES("DECLARE_RECIPES", 90), 
    TAGS("TAGS", 91), 
    ACKNOWLEDGE_PLAYER_DIGGING("ACKNOWLEDGE_PLAYER_DIGGING", 92);
    
    private static final ClientboundPackets1_14[] $VALUES;
    
    private ClientboundPackets1_14(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ClientboundPackets1_14[] { ClientboundPackets1_14.SPAWN_ENTITY, ClientboundPackets1_14.SPAWN_EXPERIENCE_ORB, ClientboundPackets1_14.SPAWN_GLOBAL_ENTITY, ClientboundPackets1_14.SPAWN_MOB, ClientboundPackets1_14.SPAWN_PAINTING, ClientboundPackets1_14.SPAWN_PLAYER, ClientboundPackets1_14.ENTITY_ANIMATION, ClientboundPackets1_14.STATISTICS, ClientboundPackets1_14.BLOCK_BREAK_ANIMATION, ClientboundPackets1_14.BLOCK_ENTITY_DATA, ClientboundPackets1_14.BLOCK_ACTION, ClientboundPackets1_14.BLOCK_CHANGE, ClientboundPackets1_14.BOSSBAR, ClientboundPackets1_14.SERVER_DIFFICULTY, ClientboundPackets1_14.CHAT_MESSAGE, ClientboundPackets1_14.MULTI_BLOCK_CHANGE, ClientboundPackets1_14.TAB_COMPLETE, ClientboundPackets1_14.DECLARE_COMMANDS, ClientboundPackets1_14.WINDOW_CONFIRMATION, ClientboundPackets1_14.CLOSE_WINDOW, ClientboundPackets1_14.WINDOW_ITEMS, ClientboundPackets1_14.WINDOW_PROPERTY, ClientboundPackets1_14.SET_SLOT, ClientboundPackets1_14.COOLDOWN, ClientboundPackets1_14.PLUGIN_MESSAGE, ClientboundPackets1_14.NAMED_SOUND, ClientboundPackets1_14.DISCONNECT, ClientboundPackets1_14.ENTITY_STATUS, ClientboundPackets1_14.EXPLOSION, ClientboundPackets1_14.UNLOAD_CHUNK, ClientboundPackets1_14.GAME_EVENT, ClientboundPackets1_14.OPEN_HORSE_WINDOW, ClientboundPackets1_14.KEEP_ALIVE, ClientboundPackets1_14.CHUNK_DATA, ClientboundPackets1_14.EFFECT, ClientboundPackets1_14.SPAWN_PARTICLE, ClientboundPackets1_14.UPDATE_LIGHT, ClientboundPackets1_14.JOIN_GAME, ClientboundPackets1_14.MAP_DATA, ClientboundPackets1_14.TRADE_LIST, ClientboundPackets1_14.ENTITY_POSITION, ClientboundPackets1_14.ENTITY_POSITION_AND_ROTATION, ClientboundPackets1_14.ENTITY_ROTATION, ClientboundPackets1_14.ENTITY_MOVEMENT, ClientboundPackets1_14.VEHICLE_MOVE, ClientboundPackets1_14.OPEN_BOOK, ClientboundPackets1_14.OPEN_WINDOW, ClientboundPackets1_14.OPEN_SIGN_EDITOR, ClientboundPackets1_14.CRAFT_RECIPE_RESPONSE, ClientboundPackets1_14.PLAYER_ABILITIES, ClientboundPackets1_14.COMBAT_EVENT, ClientboundPackets1_14.PLAYER_INFO, ClientboundPackets1_14.FACE_PLAYER, ClientboundPackets1_14.PLAYER_POSITION, ClientboundPackets1_14.UNLOCK_RECIPES, ClientboundPackets1_14.DESTROY_ENTITIES, ClientboundPackets1_14.REMOVE_ENTITY_EFFECT, ClientboundPackets1_14.RESOURCE_PACK, ClientboundPackets1_14.RESPAWN, ClientboundPackets1_14.ENTITY_HEAD_LOOK, ClientboundPackets1_14.SELECT_ADVANCEMENTS_TAB, ClientboundPackets1_14.WORLD_BORDER, ClientboundPackets1_14.CAMERA, ClientboundPackets1_14.HELD_ITEM_CHANGE, ClientboundPackets1_14.UPDATE_VIEW_POSITION, ClientboundPackets1_14.UPDATE_VIEW_DISTANCE, ClientboundPackets1_14.DISPLAY_SCOREBOARD, ClientboundPackets1_14.ENTITY_METADATA, ClientboundPackets1_14.ATTACH_ENTITY, ClientboundPackets1_14.ENTITY_VELOCITY, ClientboundPackets1_14.ENTITY_EQUIPMENT, ClientboundPackets1_14.SET_EXPERIENCE, ClientboundPackets1_14.UPDATE_HEALTH, ClientboundPackets1_14.SCOREBOARD_OBJECTIVE, ClientboundPackets1_14.SET_PASSENGERS, ClientboundPackets1_14.TEAMS, ClientboundPackets1_14.UPDATE_SCORE, ClientboundPackets1_14.SPAWN_POSITION, ClientboundPackets1_14.TIME_UPDATE, ClientboundPackets1_14.TITLE, ClientboundPackets1_14.ENTITY_SOUND, ClientboundPackets1_14.SOUND, ClientboundPackets1_14.STOP_SOUND, ClientboundPackets1_14.TAB_LIST, ClientboundPackets1_14.NBT_QUERY, ClientboundPackets1_14.COLLECT_ITEM, ClientboundPackets1_14.ENTITY_TELEPORT, ClientboundPackets1_14.ADVANCEMENTS, ClientboundPackets1_14.ENTITY_PROPERTIES, ClientboundPackets1_14.ENTITY_EFFECT, ClientboundPackets1_14.DECLARE_RECIPES, ClientboundPackets1_14.TAGS, ClientboundPackets1_14.ACKNOWLEDGE_PLAYER_DIGGING };
    }
}
