package com.viaversion.viaversion.protocols.protocol1_14to1_13_2;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ServerboundPackets1_14 implements ServerboundPacketType
{
    TELEPORT_CONFIRM("TELEPORT_CONFIRM", 0), 
    QUERY_BLOCK_NBT("QUERY_BLOCK_NBT", 1), 
    SET_DIFFICULTY("SET_DIFFICULTY", 2), 
    CHAT_MESSAGE("CHAT_MESSAGE", 3), 
    CLIENT_STATUS("CLIENT_STATUS", 4), 
    CLIENT_SETTINGS("CLIENT_SETTINGS", 5), 
    TAB_COMPLETE("TAB_COMPLETE", 6), 
    WINDOW_CONFIRMATION("WINDOW_CONFIRMATION", 7), 
    CLICK_WINDOW_BUTTON("CLICK_WINDOW_BUTTON", 8), 
    CLICK_WINDOW("CLICK_WINDOW", 9), 
    CLOSE_WINDOW("CLOSE_WINDOW", 10), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 11), 
    EDIT_BOOK("EDIT_BOOK", 12), 
    ENTITY_NBT_REQUEST("ENTITY_NBT_REQUEST", 13), 
    INTERACT_ENTITY("INTERACT_ENTITY", 14), 
    KEEP_ALIVE("KEEP_ALIVE", 15), 
    LOCK_DIFFICULTY("LOCK_DIFFICULTY", 16), 
    PLAYER_POSITION("PLAYER_POSITION", 17), 
    PLAYER_POSITION_AND_ROTATION("PLAYER_POSITION_AND_ROTATION", 18), 
    PLAYER_ROTATION("PLAYER_ROTATION", 19), 
    PLAYER_MOVEMENT("PLAYER_MOVEMENT", 20), 
    VEHICLE_MOVE("VEHICLE_MOVE", 21), 
    STEER_BOAT("STEER_BOAT", 22), 
    PICK_ITEM("PICK_ITEM", 23), 
    CRAFT_RECIPE_REQUEST("CRAFT_RECIPE_REQUEST", 24), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 25), 
    PLAYER_DIGGING("PLAYER_DIGGING", 26), 
    ENTITY_ACTION("ENTITY_ACTION", 27), 
    STEER_VEHICLE("STEER_VEHICLE", 28), 
    RECIPE_BOOK_DATA("RECIPE_BOOK_DATA", 29), 
    RENAME_ITEM("RENAME_ITEM", 30), 
    RESOURCE_PACK_STATUS("RESOURCE_PACK_STATUS", 31), 
    ADVANCEMENT_TAB("ADVANCEMENT_TAB", 32), 
    SELECT_TRADE("SELECT_TRADE", 33), 
    SET_BEACON_EFFECT("SET_BEACON_EFFECT", 34), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 35), 
    UPDATE_COMMAND_BLOCK("UPDATE_COMMAND_BLOCK", 36), 
    UPDATE_COMMAND_BLOCK_MINECART("UPDATE_COMMAND_BLOCK_MINECART", 37), 
    CREATIVE_INVENTORY_ACTION("CREATIVE_INVENTORY_ACTION", 38), 
    UPDATE_JIGSAW_BLOCK("UPDATE_JIGSAW_BLOCK", 39), 
    UPDATE_STRUCTURE_BLOCK("UPDATE_STRUCTURE_BLOCK", 40), 
    UPDATE_SIGN("UPDATE_SIGN", 41), 
    ANIMATION("ANIMATION", 42), 
    SPECTATE("SPECTATE", 43), 
    PLAYER_BLOCK_PLACEMENT("PLAYER_BLOCK_PLACEMENT", 44), 
    USE_ITEM("USE_ITEM", 45);
    
    private static final ServerboundPackets1_14[] $VALUES;
    
    private ServerboundPackets1_14(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ServerboundPackets1_14[] { ServerboundPackets1_14.TELEPORT_CONFIRM, ServerboundPackets1_14.QUERY_BLOCK_NBT, ServerboundPackets1_14.SET_DIFFICULTY, ServerboundPackets1_14.CHAT_MESSAGE, ServerboundPackets1_14.CLIENT_STATUS, ServerboundPackets1_14.CLIENT_SETTINGS, ServerboundPackets1_14.TAB_COMPLETE, ServerboundPackets1_14.WINDOW_CONFIRMATION, ServerboundPackets1_14.CLICK_WINDOW_BUTTON, ServerboundPackets1_14.CLICK_WINDOW, ServerboundPackets1_14.CLOSE_WINDOW, ServerboundPackets1_14.PLUGIN_MESSAGE, ServerboundPackets1_14.EDIT_BOOK, ServerboundPackets1_14.ENTITY_NBT_REQUEST, ServerboundPackets1_14.INTERACT_ENTITY, ServerboundPackets1_14.KEEP_ALIVE, ServerboundPackets1_14.LOCK_DIFFICULTY, ServerboundPackets1_14.PLAYER_POSITION, ServerboundPackets1_14.PLAYER_POSITION_AND_ROTATION, ServerboundPackets1_14.PLAYER_ROTATION, ServerboundPackets1_14.PLAYER_MOVEMENT, ServerboundPackets1_14.VEHICLE_MOVE, ServerboundPackets1_14.STEER_BOAT, ServerboundPackets1_14.PICK_ITEM, ServerboundPackets1_14.CRAFT_RECIPE_REQUEST, ServerboundPackets1_14.PLAYER_ABILITIES, ServerboundPackets1_14.PLAYER_DIGGING, ServerboundPackets1_14.ENTITY_ACTION, ServerboundPackets1_14.STEER_VEHICLE, ServerboundPackets1_14.RECIPE_BOOK_DATA, ServerboundPackets1_14.RENAME_ITEM, ServerboundPackets1_14.RESOURCE_PACK_STATUS, ServerboundPackets1_14.ADVANCEMENT_TAB, ServerboundPackets1_14.SELECT_TRADE, ServerboundPackets1_14.SET_BEACON_EFFECT, ServerboundPackets1_14.HELD_ITEM_CHANGE, ServerboundPackets1_14.UPDATE_COMMAND_BLOCK, ServerboundPackets1_14.UPDATE_COMMAND_BLOCK_MINECART, ServerboundPackets1_14.CREATIVE_INVENTORY_ACTION, ServerboundPackets1_14.UPDATE_JIGSAW_BLOCK, ServerboundPackets1_14.UPDATE_STRUCTURE_BLOCK, ServerboundPackets1_14.UPDATE_SIGN, ServerboundPackets1_14.ANIMATION, ServerboundPackets1_14.SPECTATE, ServerboundPackets1_14.PLAYER_BLOCK_PLACEMENT, ServerboundPackets1_14.USE_ITEM };
    }
}
