package com.viaversion.viaversion.protocols.protocol1_15to1_14_4;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ClientboundPackets1_15 implements ClientboundPacketType
{
    SPAWN_ENTITY("SPAWN_ENTITY", 0), 
    SPAWN_EXPERIENCE_ORB("SPAWN_EXPERIENCE_ORB", 1), 
    SPAWN_GLOBAL_ENTITY("SPAWN_GLOBAL_ENTITY", 2), 
    SPAWN_MOB("SPAWN_MOB", 3), 
    SPAWN_PAINTING("SPAWN_PAINTING", 4), 
    SPAWN_PLAYER("SPAWN_PLAYER", 5), 
    ENTITY_ANIMATION("ENTITY_ANIMATION", 6), 
    STATISTICS("STATISTICS", 7), 
    ACKNOWLEDGE_PLAYER_DIGGING("ACKNOWLEDGE_PLAYER_DIGGING", 8), 
    BLOCK_BREAK_ANIMATION("BLOCK_BREAK_ANIMATION", 9), 
    BLOCK_ENTITY_DATA("BLOCK_ENTITY_DATA", 10), 
    BLOCK_ACTION("BLOCK_ACTION", 11), 
    BLOCK_CHANGE("BLOCK_CHANGE", 12), 
    BOSSBAR("BOSSBAR", 13), 
    SERVER_DIFFICULTY("SERVER_DIFFICULTY", 14), 
    CHAT_MESSAGE("CHAT_MESSAGE", 15), 
    MULTI_BLOCK_CHANGE("MULTI_BLOCK_CHANGE", 16), 
    TAB_COMPLETE("TAB_COMPLETE", 17), 
    DECLARE_COMMANDS("DECLARE_COMMANDS", 18), 
    WINDOW_CONFIRMATION("WINDOW_CONFIRMATION", 19), 
    CLOSE_WINDOW("CLOSE_WINDOW", 20), 
    WINDOW_ITEMS("WINDOW_ITEMS", 21), 
    WINDOW_PROPERTY("WINDOW_PROPERTY", 22), 
    SET_SLOT("SET_SLOT", 23), 
    COOLDOWN("COOLDOWN", 24), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 25), 
    NAMED_SOUND("NAMED_SOUND", 26), 
    DISCONNECT("DISCONNECT", 27), 
    ENTITY_STATUS("ENTITY_STATUS", 28), 
    EXPLOSION("EXPLOSION", 29), 
    UNLOAD_CHUNK("UNLOAD_CHUNK", 30), 
    GAME_EVENT("GAME_EVENT", 31), 
    OPEN_HORSE_WINDOW("OPEN_HORSE_WINDOW", 32), 
    KEEP_ALIVE("KEEP_ALIVE", 33), 
    CHUNK_DATA("CHUNK_DATA", 34), 
    EFFECT("EFFECT", 35), 
    SPAWN_PARTICLE("SPAWN_PARTICLE", 36), 
    UPDATE_LIGHT("UPDATE_LIGHT", 37), 
    JOIN_GAME("JOIN_GAME", 38), 
    MAP_DATA("MAP_DATA", 39), 
    TRADE_LIST("TRADE_LIST", 40), 
    ENTITY_POSITION("ENTITY_POSITION", 41), 
    ENTITY_POSITION_AND_ROTATION("ENTITY_POSITION_AND_ROTATION", 42), 
    ENTITY_ROTATION("ENTITY_ROTATION", 43), 
    ENTITY_MOVEMENT("ENTITY_MOVEMENT", 44), 
    VEHICLE_MOVE("VEHICLE_MOVE", 45), 
    OPEN_BOOK("OPEN_BOOK", 46), 
    OPEN_WINDOW("OPEN_WINDOW", 47), 
    OPEN_SIGN_EDITOR("OPEN_SIGN_EDITOR", 48), 
    CRAFT_RECIPE_RESPONSE("CRAFT_RECIPE_RESPONSE", 49), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 50), 
    COMBAT_EVENT("COMBAT_EVENT", 51), 
    PLAYER_INFO("PLAYER_INFO", 52), 
    FACE_PLAYER("FACE_PLAYER", 53), 
    PLAYER_POSITION("PLAYER_POSITION", 54), 
    UNLOCK_RECIPES("UNLOCK_RECIPES", 55), 
    DESTROY_ENTITIES("DESTROY_ENTITIES", 56), 
    REMOVE_ENTITY_EFFECT("REMOVE_ENTITY_EFFECT", 57), 
    RESOURCE_PACK("RESOURCE_PACK", 58), 
    RESPAWN("RESPAWN", 59), 
    ENTITY_HEAD_LOOK("ENTITY_HEAD_LOOK", 60), 
    SELECT_ADVANCEMENTS_TAB("SELECT_ADVANCEMENTS_TAB", 61), 
    WORLD_BORDER("WORLD_BORDER", 62), 
    CAMERA("CAMERA", 63), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 64), 
    UPDATE_VIEW_POSITION("UPDATE_VIEW_POSITION", 65), 
    UPDATE_VIEW_DISTANCE("UPDATE_VIEW_DISTANCE", 66), 
    DISPLAY_SCOREBOARD("DISPLAY_SCOREBOARD", 67), 
    ENTITY_METADATA("ENTITY_METADATA", 68), 
    ATTACH_ENTITY("ATTACH_ENTITY", 69), 
    ENTITY_VELOCITY("ENTITY_VELOCITY", 70), 
    ENTITY_EQUIPMENT("ENTITY_EQUIPMENT", 71), 
    SET_EXPERIENCE("SET_EXPERIENCE", 72), 
    UPDATE_HEALTH("UPDATE_HEALTH", 73), 
    SCOREBOARD_OBJECTIVE("SCOREBOARD_OBJECTIVE", 74), 
    SET_PASSENGERS("SET_PASSENGERS", 75), 
    TEAMS("TEAMS", 76), 
    UPDATE_SCORE("UPDATE_SCORE", 77), 
    SPAWN_POSITION("SPAWN_POSITION", 78), 
    TIME_UPDATE("TIME_UPDATE", 79), 
    TITLE("TITLE", 80), 
    ENTITY_SOUND("ENTITY_SOUND", 81), 
    SOUND("SOUND", 82), 
    STOP_SOUND("STOP_SOUND", 83), 
    TAB_LIST("TAB_LIST", 84), 
    NBT_QUERY("NBT_QUERY", 85), 
    COLLECT_ITEM("COLLECT_ITEM", 86), 
    ENTITY_TELEPORT("ENTITY_TELEPORT", 87), 
    ADVANCEMENTS("ADVANCEMENTS", 88), 
    ENTITY_PROPERTIES("ENTITY_PROPERTIES", 89), 
    ENTITY_EFFECT("ENTITY_EFFECT", 90), 
    DECLARE_RECIPES("DECLARE_RECIPES", 91), 
    TAGS("TAGS", 92);
    
    private static final ClientboundPackets1_15[] $VALUES;
    
    private ClientboundPackets1_15(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ClientboundPackets1_15[] { ClientboundPackets1_15.SPAWN_ENTITY, ClientboundPackets1_15.SPAWN_EXPERIENCE_ORB, ClientboundPackets1_15.SPAWN_GLOBAL_ENTITY, ClientboundPackets1_15.SPAWN_MOB, ClientboundPackets1_15.SPAWN_PAINTING, ClientboundPackets1_15.SPAWN_PLAYER, ClientboundPackets1_15.ENTITY_ANIMATION, ClientboundPackets1_15.STATISTICS, ClientboundPackets1_15.ACKNOWLEDGE_PLAYER_DIGGING, ClientboundPackets1_15.BLOCK_BREAK_ANIMATION, ClientboundPackets1_15.BLOCK_ENTITY_DATA, ClientboundPackets1_15.BLOCK_ACTION, ClientboundPackets1_15.BLOCK_CHANGE, ClientboundPackets1_15.BOSSBAR, ClientboundPackets1_15.SERVER_DIFFICULTY, ClientboundPackets1_15.CHAT_MESSAGE, ClientboundPackets1_15.MULTI_BLOCK_CHANGE, ClientboundPackets1_15.TAB_COMPLETE, ClientboundPackets1_15.DECLARE_COMMANDS, ClientboundPackets1_15.WINDOW_CONFIRMATION, ClientboundPackets1_15.CLOSE_WINDOW, ClientboundPackets1_15.WINDOW_ITEMS, ClientboundPackets1_15.WINDOW_PROPERTY, ClientboundPackets1_15.SET_SLOT, ClientboundPackets1_15.COOLDOWN, ClientboundPackets1_15.PLUGIN_MESSAGE, ClientboundPackets1_15.NAMED_SOUND, ClientboundPackets1_15.DISCONNECT, ClientboundPackets1_15.ENTITY_STATUS, ClientboundPackets1_15.EXPLOSION, ClientboundPackets1_15.UNLOAD_CHUNK, ClientboundPackets1_15.GAME_EVENT, ClientboundPackets1_15.OPEN_HORSE_WINDOW, ClientboundPackets1_15.KEEP_ALIVE, ClientboundPackets1_15.CHUNK_DATA, ClientboundPackets1_15.EFFECT, ClientboundPackets1_15.SPAWN_PARTICLE, ClientboundPackets1_15.UPDATE_LIGHT, ClientboundPackets1_15.JOIN_GAME, ClientboundPackets1_15.MAP_DATA, ClientboundPackets1_15.TRADE_LIST, ClientboundPackets1_15.ENTITY_POSITION, ClientboundPackets1_15.ENTITY_POSITION_AND_ROTATION, ClientboundPackets1_15.ENTITY_ROTATION, ClientboundPackets1_15.ENTITY_MOVEMENT, ClientboundPackets1_15.VEHICLE_MOVE, ClientboundPackets1_15.OPEN_BOOK, ClientboundPackets1_15.OPEN_WINDOW, ClientboundPackets1_15.OPEN_SIGN_EDITOR, ClientboundPackets1_15.CRAFT_RECIPE_RESPONSE, ClientboundPackets1_15.PLAYER_ABILITIES, ClientboundPackets1_15.COMBAT_EVENT, ClientboundPackets1_15.PLAYER_INFO, ClientboundPackets1_15.FACE_PLAYER, ClientboundPackets1_15.PLAYER_POSITION, ClientboundPackets1_15.UNLOCK_RECIPES, ClientboundPackets1_15.DESTROY_ENTITIES, ClientboundPackets1_15.REMOVE_ENTITY_EFFECT, ClientboundPackets1_15.RESOURCE_PACK, ClientboundPackets1_15.RESPAWN, ClientboundPackets1_15.ENTITY_HEAD_LOOK, ClientboundPackets1_15.SELECT_ADVANCEMENTS_TAB, ClientboundPackets1_15.WORLD_BORDER, ClientboundPackets1_15.CAMERA, ClientboundPackets1_15.HELD_ITEM_CHANGE, ClientboundPackets1_15.UPDATE_VIEW_POSITION, ClientboundPackets1_15.UPDATE_VIEW_DISTANCE, ClientboundPackets1_15.DISPLAY_SCOREBOARD, ClientboundPackets1_15.ENTITY_METADATA, ClientboundPackets1_15.ATTACH_ENTITY, ClientboundPackets1_15.ENTITY_VELOCITY, ClientboundPackets1_15.ENTITY_EQUIPMENT, ClientboundPackets1_15.SET_EXPERIENCE, ClientboundPackets1_15.UPDATE_HEALTH, ClientboundPackets1_15.SCOREBOARD_OBJECTIVE, ClientboundPackets1_15.SET_PASSENGERS, ClientboundPackets1_15.TEAMS, ClientboundPackets1_15.UPDATE_SCORE, ClientboundPackets1_15.SPAWN_POSITION, ClientboundPackets1_15.TIME_UPDATE, ClientboundPackets1_15.TITLE, ClientboundPackets1_15.ENTITY_SOUND, ClientboundPackets1_15.SOUND, ClientboundPackets1_15.STOP_SOUND, ClientboundPackets1_15.TAB_LIST, ClientboundPackets1_15.NBT_QUERY, ClientboundPackets1_15.COLLECT_ITEM, ClientboundPackets1_15.ENTITY_TELEPORT, ClientboundPackets1_15.ADVANCEMENTS, ClientboundPackets1_15.ENTITY_PROPERTIES, ClientboundPackets1_15.ENTITY_EFFECT, ClientboundPackets1_15.DECLARE_RECIPES, ClientboundPackets1_15.TAGS };
    }
}
