package com.viaversion.viaversion.protocols.protocol1_16to1_15_2;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ServerboundPackets1_16 implements ServerboundPacketType
{
    TELEPORT_CONFIRM("TELEPORT_CONFIRM", 0), 
    QUERY_BLOCK_NBT("QUERY_BLOCK_NBT", 1), 
    SET_DIFFICULTY("SET_DIFFICULTY", 2), 
    CHAT_MESSAGE("CHAT_MESSAGE", 3), 
    CLIENT_STATUS("CLIENT_STATUS", 4), 
    CLIENT_SETTINGS("CLIENT_SETTINGS", 5), 
    TAB_COMPLETE("TAB_COMPLETE", 6), 
    WINDOW_CONFIRMATION("WINDOW_CONFIRMATION", 7), 
    CLICK_WINDOW_BUTTON("CLICK_WINDOW_BUTTON", 8), 
    CLICK_WINDOW("CLICK_WINDOW", 9), 
    CLOSE_WINDOW("CLOSE_WINDOW", 10), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 11), 
    EDIT_BOOK("EDIT_BOOK", 12), 
    ENTITY_NBT_REQUEST("ENTITY_NBT_REQUEST", 13), 
    INTERACT_ENTITY("INTERACT_ENTITY", 14), 
    GENERATE_JIGSAW("GENERATE_JIGSAW", 15), 
    KEEP_ALIVE("KEEP_ALIVE", 16), 
    LOCK_DIFFICULTY("LOCK_DIFFICULTY", 17), 
    PLAYER_POSITION("PLAYER_POSITION", 18), 
    PLAYER_POSITION_AND_ROTATION("PLAYER_POSITION_AND_ROTATION", 19), 
    PLAYER_ROTATION("PLAYER_ROTATION", 20), 
    PLAYER_MOVEMENT("PLAYER_MOVEMENT", 21), 
    VEHICLE_MOVE("VEHICLE_MOVE", 22), 
    STEER_BOAT("STEER_BOAT", 23), 
    PICK_ITEM("PICK_ITEM", 24), 
    CRAFT_RECIPE_REQUEST("CRAFT_RECIPE_REQUEST", 25), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 26), 
    PLAYER_DIGGING("PLAYER_DIGGING", 27), 
    ENTITY_ACTION("ENTITY_ACTION", 28), 
    STEER_VEHICLE("STEER_VEHICLE", 29), 
    RECIPE_BOOK_DATA("RECIPE_BOOK_DATA", 30), 
    RENAME_ITEM("RENAME_ITEM", 31), 
    RESOURCE_PACK_STATUS("RESOURCE_PACK_STATUS", 32), 
    ADVANCEMENT_TAB("ADVANCEMENT_TAB", 33), 
    SELECT_TRADE("SELECT_TRADE", 34), 
    SET_BEACON_EFFECT("SET_BEACON_EFFECT", 35), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 36), 
    UPDATE_COMMAND_BLOCK("UPDATE_COMMAND_BLOCK", 37), 
    UPDATE_COMMAND_BLOCK_MINECART("UPDATE_COMMAND_BLOCK_MINECART", 38), 
    CREATIVE_INVENTORY_ACTION("CREATIVE_INVENTORY_ACTION", 39), 
    UPDATE_JIGSAW_BLOCK("UPDATE_JIGSAW_BLOCK", 40), 
    UPDATE_STRUCTURE_BLOCK("UPDATE_STRUCTURE_BLOCK", 41), 
    UPDATE_SIGN("UPDATE_SIGN", 42), 
    ANIMATION("ANIMATION", 43), 
    SPECTATE("SPECTATE", 44), 
    PLAYER_BLOCK_PLACEMENT("PLAYER_BLOCK_PLACEMENT", 45), 
    USE_ITEM("USE_ITEM", 46);
    
    private static final ServerboundPackets1_16[] $VALUES;
    
    private ServerboundPackets1_16(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ServerboundPackets1_16[] { ServerboundPackets1_16.TELEPORT_CONFIRM, ServerboundPackets1_16.QUERY_BLOCK_NBT, ServerboundPackets1_16.SET_DIFFICULTY, ServerboundPackets1_16.CHAT_MESSAGE, ServerboundPackets1_16.CLIENT_STATUS, ServerboundPackets1_16.CLIENT_SETTINGS, ServerboundPackets1_16.TAB_COMPLETE, ServerboundPackets1_16.WINDOW_CONFIRMATION, ServerboundPackets1_16.CLICK_WINDOW_BUTTON, ServerboundPackets1_16.CLICK_WINDOW, ServerboundPackets1_16.CLOSE_WINDOW, ServerboundPackets1_16.PLUGIN_MESSAGE, ServerboundPackets1_16.EDIT_BOOK, ServerboundPackets1_16.ENTITY_NBT_REQUEST, ServerboundPackets1_16.INTERACT_ENTITY, ServerboundPackets1_16.GENERATE_JIGSAW, ServerboundPackets1_16.KEEP_ALIVE, ServerboundPackets1_16.LOCK_DIFFICULTY, ServerboundPackets1_16.PLAYER_POSITION, ServerboundPackets1_16.PLAYER_POSITION_AND_ROTATION, ServerboundPackets1_16.PLAYER_ROTATION, ServerboundPackets1_16.PLAYER_MOVEMENT, ServerboundPackets1_16.VEHICLE_MOVE, ServerboundPackets1_16.STEER_BOAT, ServerboundPackets1_16.PICK_ITEM, ServerboundPackets1_16.CRAFT_RECIPE_REQUEST, ServerboundPackets1_16.PLAYER_ABILITIES, ServerboundPackets1_16.PLAYER_DIGGING, ServerboundPackets1_16.ENTITY_ACTION, ServerboundPackets1_16.STEER_VEHICLE, ServerboundPackets1_16.RECIPE_BOOK_DATA, ServerboundPackets1_16.RENAME_ITEM, ServerboundPackets1_16.RESOURCE_PACK_STATUS, ServerboundPackets1_16.ADVANCEMENT_TAB, ServerboundPackets1_16.SELECT_TRADE, ServerboundPackets1_16.SET_BEACON_EFFECT, ServerboundPackets1_16.HELD_ITEM_CHANGE, ServerboundPackets1_16.UPDATE_COMMAND_BLOCK, ServerboundPackets1_16.UPDATE_COMMAND_BLOCK_MINECART, ServerboundPackets1_16.CREATIVE_INVENTORY_ACTION, ServerboundPackets1_16.UPDATE_JIGSAW_BLOCK, ServerboundPackets1_16.UPDATE_STRUCTURE_BLOCK, ServerboundPackets1_16.UPDATE_SIGN, ServerboundPackets1_16.ANIMATION, ServerboundPackets1_16.SPECTATE, ServerboundPackets1_16.PLAYER_BLOCK_PLACEMENT, ServerboundPackets1_16.USE_ITEM };
    }
}
