package Mood.creativetab;

import net.minecraft.creativetab.*;
import Mood.creativetab.Util.*;
import net.minecraft.item.*;
import java.util.*;

public class MoodTabZaszlok extends CreativeTabs
{
    public MoodTabZaszlok() {
        super("MoodTabZaszlok");
        this.setBackgroundImageName("item_search.png");
    }
    
    @Override
    public void displayAllReleventItems(final List list) {
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"br\",Color:0},1:{Pattern:\"mr\",Color:15},2:{Pattern:\"ld\",Color:0},3:{Pattern:\"ts\",Color:0},4:{Pattern:\"ls\",Color:0}],Base:15}}").setStackDisplayName("§e§lBal-fels\u0151"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ts\",Color:0},1:{Pattern:\"bs\",Color:0},2:{Pattern:\"bt\",Color:15}],Base:15}}").setStackDisplayName("§e§lFels\u0151-K\u00f6z\u00e9p"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bl\",Color:0},1:{Pattern:\"mr\",Color:15},2:{Pattern:\"rud\",Color:0},3:{Pattern:\"ts\",Color:0},4:{Pattern:\"rs\",Color:0}],Base:15}}").setStackDisplayName("§e§lJobb-Fels\u0151"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bts\",Color:0},1:{Pattern:\"cre\",Color:0},2:{Pattern:\"moj\",Color:3},3:{Pattern:\"ms\",Color:11},4:{Pattern:\"gra\",Color:3},5:{Pattern:\"cbo\",Color:2},6:{Pattern:\"tt\",Color:2},7:{Pattern:\"mc\",Color:2},8:{Pattern:\"bo\",Color:2}],Base:14}}").setStackDisplayName("§6§l\u0150z"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mr\",Color:15},1:{Pattern:\"dls\",Color:12},2:{Pattern:\"flo\",Color:0},3:{Pattern:\"ts\",Color:15},4:{Pattern:\"bs\",Color:15},5:{Pattern:\"cbo\",Color:15}],Base:0}}").setStackDisplayName("§9§lEnderPearl"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ms\",Color:12},1:{Pattern:\"vhr\",Color:1},2:{Pattern:\"bo\",Color:0},3:{Pattern:\"bts\",Color:0},4:{Pattern:\"ts\",Color:0}],Base:1}}").setStackDisplayName("§4§lSUS §e§l(Amongus)"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bts\",Color:1},1:{Pattern:\"cbo\",Color:15},2:{Pattern:\"hh\",Color:15},3:{Pattern:\"mc\",Color:15},4:{Pattern:\"cre\",Color:15},5:{Pattern:\"sku\",Color:15}],Base:0}}").setStackDisplayName("§f§lK\u00eds\u00e9rtet"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cbo\",Color:11},1:{Pattern:\"rs\",Color:15},2:{Pattern:\"ss\",Color:3},3:{Pattern:\"hhb\",Color:15},4:{Pattern:\"bo\",Color:15}],Base:3}}").setStackDisplayName("§6§lK\u00f6nyv"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bs\",Color:7},1:{Pattern:\"bt\",Color:15},2:{Pattern:\"cre\",Color:0},3:{Pattern:\"flo\",Color:0},4:{Pattern:\"bo\",Color:2},5:{Pattern:\"mc\",Color:3},6:{Pattern:\"cr\",Color:15},7:{Pattern:\"sku\",Color:3},8:{Pattern:\"bts\",Color:15},9:{Pattern:\"tt\",Color:2},10:{Pattern:\"tt\",Color:2},11:{Pattern:\"tt\",Color:2}],Base:12}}").setStackDisplayName("§e§lMacska"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"vh\",Color:0},1:{Pattern:\"hhb\",Color:15},2:{Pattern:\"ls\",Color:0},3:{Pattern:\"mr\",Color:15},4:{Pattern:\"bts\",Color:0},5:{Pattern:\"bl\",Color:0}],Base:15}}").setStackDisplayName("§e§lBal-K\u00f6z\u00e9p"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ss\",Color:0},1:{Pattern:\"rs\",Color:15},2:{Pattern:\"ls\",Color:15},3:{Pattern:\"ts\",Color:15},4:{Pattern:\"hhb\",Color:15},5:{Pattern:\"bts\",Color:0}],Base:15}}").setStackDisplayName("§e§lK\u00f6z\u00e9p"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"vhr\",Color:0},1:{Pattern:\"hhb\",Color:15},2:{Pattern:\"rs\",Color:0},3:{Pattern:\"mr\",Color:15},4:{Pattern:\"bts\",Color:0},5:{Pattern:\"br\",Color:0}],Base:15}}").setStackDisplayName("§e§lJobb-K\u00f6z\u00e9p"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"flo\",Color:7},1:{Pattern:\"dls\",Color:3},2:{Pattern:\"rud\",Color:15},3:{Pattern:\"drs\",Color:7},4:{Pattern:\"br\",Color:15},5:{Pattern:\"cbo\",Color:15}],Base:15}}").setStackDisplayName("§e§lFegyver"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bri\",Color:4},1:{Pattern:\"cbo\",Color:0},2:{Pattern:\"ts\",Color:0},3:{Pattern:\"hhb\",Color:15},4:{Pattern:\"bo\",Color:0},5:{Pattern:\"bts\",Color:15}],Base:15}}").setStackDisplayName("§9§lR2-D2"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"moj\",Color:15},1:{Pattern:\"flo\",Color:0},2:{Pattern:\"gru\",Color:5},3:{Pattern:\"mc\",Color:15},4:{Pattern:\"bt\",Color:7},5:{Pattern:\"bts\",Color:0}],Base:0}}").setStackDisplayName("§5§lMoonlight"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ts\",Color:0},1:{Pattern:\"bs\",Color:0},2:{Pattern:\"rs\",Color:0},3:{Pattern:\"ls\",Color:0},4:{Pattern:\"mc\",Color:0},5:{Pattern:\"bt\",Color:0}],Base:15}}").setStackDisplayName("§f§lHerobrine"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mr\",Color:0},1:{Pattern:\"cbo\",Color:14},2:{Pattern:\"mc\",Color:14},3:{Pattern:\"cre\",Color:14},4:{Pattern:\"tt\",Color:14}],Base:15}}").setStackDisplayName("§6§lR\u00f3ka"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ss\",Color:11},1:{Pattern:\"bs\",Color:3},2:{Pattern:\"bo\",Color:12},3:{Pattern:\"bo\",Color:12},4:{Pattern:\"bt\",Color:3},5:{Pattern:\"mr\",Color:9},6:{Pattern:\"flo\",Color:0},7:{Pattern:\"cre\",Color:0},8:{Pattern:\"sku\",Color:3},9:{Pattern:\"tt\",Color:12},10:{Pattern:\"ts\",Color:12},11:{Pattern:\"mc\",Color:3}],Base:12}}").setStackDisplayName("§e§lKutya"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cbo\",Color:0},1:{Pattern:\"tt\",Color:0},2:{Pattern:\"lud\",Color:0},3:{Pattern:\"bo\",Color:0},4:{Pattern:\"bs\",Color:0}],Base:15}}").setStackDisplayName("§e§lBal-Als\u00f3"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cbo\",Color:15},1:{Pattern:\"bt\",Color:15},2:{Pattern:\"ms\",Color:0},3:{Pattern:\"hh\",Color:0},4:{Pattern:\"bs\",Color:0}],Base:0}}").setStackDisplayName("§e§lAls\u00f3-K\u00f6z\u00e9p"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cbo\",Color:0},1:{Pattern:\"tt\",Color:0},2:{Pattern:\"rd\",Color:0},3:{Pattern:\"bo\",Color:0},4:{Pattern:\"bs\",Color:0}],Base:15}}").setStackDisplayName("§e§lJobb-Als\u00f3"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ls\",Color:0},1:{Pattern:\"rs\",Color:0},2:{Pattern:\"ms\",Color:0},3:{Pattern:\"ts\",Color:0},4:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lA\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"rs\",Color:0},1:{Pattern:\"bs\",Color:0},2:{Pattern:\"ts\",Color:0},3:{Pattern:\"cbo\",Color:15},4:{Pattern:\"ls\",Color:0},5:{Pattern:\"ms\",Color:0},6:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lB\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"bs\",Color:0},1:{Pattern:\"ts\",Color:0},2:{Pattern:\"rs\",Color:0},3:{Pattern:\"ms\",Color:15},4:{Pattern:\"ls\",Color:0},5:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lC\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ts\",Color:0},1:{Pattern:\"rs\",Color:0},2:{Pattern:\"bs\",Color:0},3:{Pattern:\"cbo\",Color:15},4:{Pattern:\"ls\",Color:0},5:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lD\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ms\",Color:0},1:{Pattern:\"ls\",Color:0},2:{Pattern:\"ts\",Color:0},3:{Pattern:\"bs\",Color:0},4:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lE\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"bs\",Color:15},1:{Pattern:\"hh\",Color:15},2:{Pattern:\"ts\",Color:0},3:{Pattern:\"ls\",Color:0},4:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lF\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"rs\",Color:0},1:{Pattern:\"ms\",Color:0},2:{Pattern:\"hh\",Color:15},3:{Pattern:\"vh\",Color:15},4:{Pattern:\"bs\",Color:0},5:{Pattern:\"ls\",Color:0},6:{Pattern:\"ts\",Color:0},7:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lG\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ls\",Color:0},1:{Pattern:\"rs\",Color:0},2:{Pattern:\"ms\",Color:0},3:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lH\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ts\",Color:0},1:{Pattern:\"bs\",Color:0},2:{Pattern:\"cs\",Color:0},3:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lI\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"cs\",Color:0},1:{Pattern:\"ts\",Color:0},2:{Pattern:\"bl\",Color:0},3:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lJ\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ls\",Color:0},1:{Pattern:\"cr\",Color:0},2:{Pattern:\"vh\",Color:0},3:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lK\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"vh\",Color:0},1:{Pattern:\"bs\",Color:0},2:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lL\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"rs\",Color:0},1:{Pattern:\"ls\",Color:0},2:{Pattern:\"tt\",Color:0},3:{Pattern:\"bo\",Color:15},4:{Pattern:\"tts\",Color:15}],Base:15},display:{Lore:[0:\"§5§lM\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"drs\",Color:0},1:{Pattern:\"ls\",Color:0},2:{Pattern:\"rs\",Color:0},3:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lN\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"bs\",Color:0},1:{Pattern:\"ts\",Color:0},2:{Pattern:\"rs\",Color:0},3:{Pattern:\"ls\",Color:0},4:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lO\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ts\",Color:0},1:{Pattern:\"rs\",Color:0},2:{Pattern:\"ms\",Color:0},3:{Pattern:\"hhb\",Color:15},4:{Pattern:\"ls\",Color:0},5:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lP\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ls\",Color:0},1:{Pattern:\"ts\",Color:0},2:{Pattern:\"rs\",Color:0},3:{Pattern:\"bs\",Color:0},4:{Pattern:\"bo\",Color:15},5:{Pattern:\"br\",Color:0}],Base:15},display:{Lore:[0:\"§5§lQ\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"rs\",Color:0},1:{Pattern:\"ts\",Color:0},2:{Pattern:\"hhb\",Color:15},3:{Pattern:\"ls\",Color:0},4:{Pattern:\"ms\",Color:0},5:{Pattern:\"drs\",Color:0},6:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lR\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"tt\",Color:0},1:{Pattern:\"bt\",Color:0},2:{Pattern:\"tr\",Color:0},3:{Pattern:\"bl\",Color:0},4:{Pattern:\"mr\",Color:15},5:{Pattern:\"drs\",Color:0},6:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lS\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"cs\",Color:0},1:{Pattern:\"ts\",Color:0},2:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lT\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ls\",Color:0},1:{Pattern:\"rs\",Color:0},2:{Pattern:\"bs\",Color:0},3:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lU\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"bt\",Color:0},1:{Pattern:\"bts\",Color:15},2:{Pattern:\"rs\",Color:0},3:{Pattern:\"ls\",Color:0},4:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lW\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"cr\",Color:0},1:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lX\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"bo\",Color:15},1:{Pattern:\"cr\",Color:0},2:{Pattern:\"rd\",Color:15},3:{Pattern:\"dls\",Color:0},4:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lY\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ts\",Color:0},1:{Pattern:\"bs\",Color:0},2:{Pattern:\"dls\",Color:0},3:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§lZ\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"hh\",Color:0},1:{Pattern:\"ms\",Color:0},2:{Pattern:\"bl\",Color:0},3:{Pattern:\"vhr\",Color:15},4:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§l!\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"rs\",Color:0},1:{Pattern:\"hhb\",Color:15},2:{Pattern:\"ts\",Color:0},3:{Pattern:\"ms\",Color:0},4:{Pattern:\"bl\",Color:0},5:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§l?\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"cs\",Color:0},1:{Pattern:\"ms\",Color:15},2:{Pattern:\"ts\",Color:15},3:{Pattern:\"bs\",Color:15}],Base:15},display:{Lore:[0:\"§5§l:\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"bl\",Color:0},1:{Pattern:\"bo\",Color:15}],Base:15},display:{Lore:[0:\"§5§l.\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{x:-3987,y:65,z:-14676,id:\"Banner\",Patterns:[0:{Pattern:\"cre\",Color:1},1:{Pattern:\"sku\",Color:11},2:{Pattern:\"flo\",Color:2},3:{Pattern:\"mc\",Color:3}],Base:15},display:{Lore:[0:\"§e§lKar\u00e1csonyi D\u00edsz\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{x:-3987,y:65,z:-14677,id:\"Banner\",Patterns:[0:{Pattern:\"bri\",Color:2},1:{Pattern:\"bo\",Color:0},2:{Pattern:\"sc\",Color:2},3:{Pattern:\"mc\",Color:11},4:{Pattern:\"rud\",Color:0},5:{Pattern:\"ld\",Color:0}],Base:15},display:{Lore:[0:\"§e§lKar\u00e1csonyfa\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{x:-3987,y:65,z:-14678,id:\"Banner\",Patterns:[0:{Pattern:\"sku\",Color:0},1:{Pattern:\"flo\",Color:15},2:{Pattern:\"cr\",Color:15},3:{Pattern:\"cbo\",Color:12},4:{Pattern:\"bo\",Color:12},5:{Pattern:\"ts\",Color:12}],Base:15},display:{Lore:[0:\"§f§lH\u00f3ember\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{x:-3987,y:65,z:-14679,id:\"Banner\",Patterns:[0:{Pattern:\"sc\",Color:1},1:{Pattern:\"flo\",Color:1},2:{Pattern:\"hh\",Color:12},3:{Pattern:\"ms\",Color:12},4:{Pattern:\"bo\",Color:12}],Base:15},display:{Lore:[0:\"§e§lAj\u00e1nd\u00e9k\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{x:-3987,y:65,z:-14680,id:\"Banner\",Patterns:[0:{Pattern:\"mr\",Color:1},1:{Pattern:\"cre\",Color:14},2:{Pattern:\"ms\",Color:15},3:{Pattern:\"hh\",Color:1},4:{Pattern:\"cbo\",Color:2},5:{Pattern:\"ts\",Color:2}],Base:15},display:{Lore:[0:\"§4§lM§f§li§4§lk§f§lu§4§ll§f§l\u00e1§4§ls\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{x:-3987,y:65,z:-14679,id:\"Banner\",Patterns:[0:{Pattern:\"sc\",Color:1},1:{Pattern:\"flo\",Color:1},2:{Pattern:\"hh\",Color:12},3:{Pattern:\"ms\",Color:12},4:{Pattern:\"bo\",Color:12}],Base:15},display:{Lore:[0:\"§e§lAj\u00e1nd\u00e9k\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"dls\",Color:15},1:{Pattern:\"dls\",Color:15},2:{Pattern:\"drs\",Color:15},3:{Pattern:\"drs\",Color:15},4:{Pattern:\"cr\",Color:1},5:{Pattern:\"cr\",Color:1},6:{Pattern:\"cs\",Color:15},7:{Pattern:\"cs\",Color:15},8:{Pattern:\"ms\",Color:15},9:{Pattern:\"ms\",Color:15},10:{Pattern:\"sc\",Color:1},11:{Pattern:\"sc\",Color:1}],Base:4},display:{Lore:[0:\"§e§oUnited kingdom\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ls\",Color:4},1:{Pattern:\"rs\",Color:1}],Base:15},display:{Lore:[0:\"§e§oFrench\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ls\",Color:0},1:{Pattern:\"ls\",Color:0},2:{Pattern:\"rs\",Color:11},3:{Pattern:\"rs\",Color:11}],Base:1},display:{Lore:[0:\"§e§oGerman\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ls\",Color:15},1:{Pattern:\"ls\",Color:15},2:{Pattern:\"rs\",Color:1},3:{Pattern:\"rs\",Color:1}],Base:4},display:{Lore:[0:\"§e§oRussia\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"mc\",Color:1},1:{Pattern:\"mc\",Color:1}],Base:15},display:{Lore:[0:\"§e§oJapan\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"mr\",Color:11},1:{Pattern:\"mr\",Color:11},2:{Pattern:\"mc\",Color:4},3:{Pattern:\"mc\",Color:4}],Base:2},display:{Lore:[0:\"§e§oBrazil\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"sc\",Color:3},1:{Pattern:\"sc\",Color:3},2:{Pattern:\"ts\",Color:11},3:{Pattern:\"hhb\",Color:11},4:{Pattern:\"ms\",Color:11},5:{Pattern:\"ls\",Color:1},6:{Pattern:\"ls\",Color:1},7:{Pattern:\"rs\",Color:1},8:{Pattern:\"rs\",Color:1}],Base:11},display:{Lore:[0:\"§e§oSpain\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ms\",Color:14},1:{Pattern:\"ss\",Color:15},2:{Pattern:\"ls\",Color:12},3:{Pattern:\"ls\",Color:12},4:{Pattern:\"rs\",Color:12},5:{Pattern:\"rs\",Color:12}],Base:15},display:{Lore:[0:\"§e§oArgentine\"]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ts\",Color:14},1:{Pattern:\"ts\",Color:14},2:{Pattern:\"bs\",Color:2},3:{Pattern:\"bs\",Color:2}],Base:15},display:{Lore:[0:\"§e§oIndia\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ls\",Color:1},1:{Pattern:\"ls\",Color:1},2:{Pattern:\"rs\",Color:2},3:{Pattern:\"rs\",Color:2}],Base:15},display:{Lore:[0:\"§e§oHungary\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"vhr\",Color:11}],Base:12},display:{Lore:[0:\"§e§oUkraine\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{id:\"Banner\",Patterns:[0:{Pattern:\"ts\",Color:4},1:{Pattern:\"ts\",Color:4},2:{Pattern:\"bs\",Color:1},3:{Pattern:\"bs\",Color:1}],Base:11},display:{Lore:[0:\"§e§oRomania\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bs\",Color:7},1:{Pattern:\"bts\",Color:0},2:{Pattern:\"cbo\",Color:7},3:{Pattern:\"hh\",Color:6}],Base:6},display:{Lore:[0:\"§7§lKoala\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ss\",Color:10},1:{Pattern:\"drs\",Color:10},2:{Pattern:\"cr\",Color:10},3:{Pattern:\"cs\",Color:0},4:{Pattern:\"ts\",Color:0},5:{Pattern:\"hhb\",Color:0}],Base:0},display:{Lore:[0:\"§0§lS\u00e1rk\u00e1ny\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"tt\",Color:1},1:{Pattern:\"mr\",Color:11},2:{Pattern:\"hhb\",Color:4},3:{Pattern:\"bts\",Color:15},4:{Pattern:\"flo\",Color:11},5:{Pattern:\"ms\",Color:11}],Base:11},display:{Lore:[0:\"§e§lArany Sas\"]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"flo\",Color:0},1:{Pattern:\"sku\",Color:15},2:{Pattern:\"mc\",Color:15},3:{Pattern:\"ts\",Color:15},4:{Pattern:\"hh\",Color:15}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cs\",Color:0},1:{Pattern:\"tts\",Color:8},2:{Pattern:\"flo\",Color:11},3:{Pattern:\"gru\",Color:0},4:{Pattern:\"flo\",Color:0},5:{Pattern:\"cre\",Color:0}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"flo\",Color:15},1:{Pattern:\"hhb\",Color:0},2:{Pattern:\"bt\",Color:10},3:{Pattern:\"mr\",Color:10},4:{Pattern:\"tt\",Color:0},5:{Pattern:\"mc\",Color:10}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mc\",Color:4},1:{Pattern:\"ss\",Color:15},2:{Pattern:\"cr\",Color:15},3:{Pattern:\"bt\",Color:1},4:{Pattern:\"sku\",Color:15},5:{Pattern:\"bs\",Color:15}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ts\",Color:1},1:{Pattern:\"lud\",Color:2},2:{Pattern:\"rd\",Color:11},3:{Pattern:\"tr\",Color:1},4:{Pattern:\"tr\",Color:1},5:{Pattern:\"mc\",Color:12}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mc\",Color:15},1:{Pattern:\"flo\",Color:15},2:{Pattern:\"cr\",Color:15},3:{Pattern:\"ms\",Color:0},4:{Pattern:\"cbo\",Color:5},5:{Pattern:\"bt\",Color:15}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mr\",Color:7},1:{Pattern:\"flo\",Color:2},2:{Pattern:\"moj\",Color:3},3:{Pattern:\"mc\",Color:10},4:{Pattern:\"ms\",Color:11},5:{Pattern:\"hhb\",Color:6}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bt\",Color:15},1:{Pattern:\"bts\",Color:8},2:{Pattern:\"dls\",Color:4},3:{Pattern:\"mr\",Color:4},4:{Pattern:\"gra\",Color:0},5:{Pattern:\"tl\",Color:15}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cs\",Color:15},1:{Pattern:\"tr\",Color:15},2:{Pattern:\"ms\",Color:15},3:{Pattern:\"bo\",Color:4}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ss\",Color:11},1:{Pattern:\"rs\",Color:11},2:{Pattern:\"ls\",Color:11},3:{Pattern:\"bo\",Color:11},4:{Pattern:\"ms\",Color:11},5:{Pattern:\"bs\",Color:11}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"dls\",Color:0},1:{Pattern:\"cr\",Color:8},2:{Pattern:\"mc\",Color:15},3:{Pattern:\"hhb\",Color:15},4:{Pattern:\"ls\",Color:8},5:{Pattern:\"rs\",Color:8}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bs\",Color:1},1:{Pattern:\"cre\",Color:15},2:{Pattern:\"cbo\",Color:15},3:{Pattern:\"cs\",Color:15},4:{Pattern:\"ts\",Color:15},5:{Pattern:\"tts\",Color:10}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mc\",Color:15},1:{Pattern:\"cre\",Color:0},2:{Pattern:\"flo\",Color:15},3:{Pattern:\"ss\",Color:15},4:{Pattern:\"ts\",Color:0},5:{Pattern:\"bo\",Color:0}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mr\",Color:0},1:{Pattern:\"bts\",Color:0},2:{Pattern:\"sku\",Color:7},3:{Pattern:\"mc\",Color:15},4:{Pattern:\"bo\",Color:0},5:{Pattern:\"tt\",Color:0}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ts\",Color:10},1:{Pattern:\"bs\",Color:1},2:{Pattern:\"ts\",Color:10},3:{Pattern:\"cbo\",Color:0},4:{Pattern:\"bo\",Color:0},5:{Pattern:\"cbo\",Color:0}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"hhb\",Color:0},1:{Pattern:\"cr\",Color:3},2:{Pattern:\"flo\",Color:3},3:{Pattern:\"bo\",Color:7},4:{Pattern:\"cbo\",Color:7},5:{Pattern:\"mc\",Color:3}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"moj\",Color:14},1:{Pattern:\"cbo\",Color:15},2:{Pattern:\"hh\",Color:15},3:{Pattern:\"ts\",Color:0},4:{Pattern:\"drs\",Color:0},5:{Pattern:\"vhr\",Color:0}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"gru\",Color:9},1:{Pattern:\"mr\",Color:8},2:{Pattern:\"mc\",Color:0},3:{Pattern:\"bs\",Color:8},4:{Pattern:\"cbo\",Color:13},5:{Pattern:\"bts\",Color:8}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cbo\",Color:15},1:{Pattern:\"bt\",Color:14},2:{Pattern:\"mc\",Color:14},3:{Pattern:\"bo\",Color:0},4:{Pattern:\"bs\",Color:0},5:{Pattern:\"hh\",Color:0}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ls\",Color:1},1:{Pattern:\"rs\",Color:1},2:{Pattern:\"gra\",Color:0},3:{Pattern:\"drs\",Color:1},4:{Pattern:\"bo\",Color:0}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bri\",Color:7},1:{Pattern:\"cs\",Color:3},2:{Pattern:\"ss\",Color:3},3:{Pattern:\"ss\",Color:3},4:{Pattern:\"bo\",Color:7}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ss\",Color:13},1:{Pattern:\"bri\",Color:5},2:{Pattern:\"cbo\",Color:13},3:{Pattern:\"bo\",Color:0}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cre\",Color:15},1:{Pattern:\"cs\",Color:15},2:{Pattern:\"bs\",Color:12},3:{Pattern:\"cbo\",Color:12}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"flo\",Color:2},1:{Pattern:\"moj\",Color:10},2:{Pattern:\"lud\",Color:0},3:{Pattern:\"tl\",Color:1},4:{Pattern:\"tts\",Color:0},5:{Pattern:\"cbo\",Color:0}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bts\",Color:1},1:{Pattern:\"br\",Color:1},2:{Pattern:\"mr\",Color:11},3:{Pattern:\"gra\",Color:14},4:{Pattern:\"mc\",Color:14},5:{Pattern:\"mc\",Color:15}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ss\",Color:15},1:{Pattern:\"ts\",Color:0},2:{Pattern:\"flo\",Color:15},3:{Pattern:\"bt\",Color:0},4:{Pattern:\"cs\",Color:0}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mc\",Color:15},1:{Pattern:\"bri\",Color:2},2:{Pattern:\"bt\",Color:3},3:{Pattern:\"br\",Color:3},4:{Pattern:\"bl\",Color:2},5:{Pattern:\"bts\",Color:2}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"hh\",Color:4},1:{Pattern:\"ss\",Color:15},2:{Pattern:\"sc\",Color:11},3:{Pattern:\"hhb\",Color:1},4:{Pattern:\"br\",Color:9},5:{Pattern:\"bo\",Color:11}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bri\",Color:15},1:{Pattern:\"hhb\",Color:4},2:{Pattern:\"sc\",Color:0},3:{Pattern:\"sc\",Color:4},4:{Pattern:\"bo\",Color:0},5:{Pattern:\"bo\",Color:4}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mr\",Color:2},1:{Pattern:\"cre\",Color:2},2:{Pattern:\"ms\",Color:12},3:{Pattern:\"mc\",Color:11},4:{Pattern:\"mc\",Color:3}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"ms\",Color:15},1:{Pattern:\"cs\",Color:6},2:{Pattern:\"cbo\",Color:0},3:{Pattern:\"ts\",Color:6},4:{Pattern:\"hhb\",Color:6},5:{Pattern:\"bo\",Color:6}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"dls\",Color:15},1:{Pattern:\"gra\",Color:4},2:{Pattern:\"gra\",Color:15},3:{Pattern:\"gra\",Color:4},4:{Pattern:\"tts\",Color:11},5:{Pattern:\"bo\",Color:11}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"bs\",Color:5},1:{Pattern:\"mr\",Color:15},2:{Pattern:\"bl\",Color:5},3:{Pattern:\"ts\",Color:5},4:{Pattern:\"bo\",Color:5}]}}\r\n"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"cbo\",Color:10},1:{Pattern:\"mr\",Color:10},2:{Pattern:\"glb\",Color:4},3:{Pattern:\"ld\",Color:0},4:{Pattern:\"tl\",Color:11},5:{Pattern:\"tl\",Color:15}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"mr\",Color:15},1:{Pattern:\"tt\",Color:0},2:{Pattern:\"sc\",Color:15},3:{Pattern:\"bo\",Color:0},4:{Pattern:\"bs\",Color:0},5:{Pattern:\"tr\",Color:0}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[0:{Pattern:\"mr\",Color:9},1:{Pattern:\"ls\",Color:15},2:{Pattern:\"rs\",Color:15},3:{Pattern:\"bt\",Color:9},4:{Pattern:\"bts\",Color:15}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[0:{Pattern:\"cre\",Color:0},1:{Pattern:\"cs\",Color:0},2:{Pattern:\"mr\",Color:0},3:{Pattern:\"tt\",Color:15},4:{Pattern:\"cbo\",Color:15},5:{Pattern:\"cr\",Color:15}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 14 {BlockEntityTag:{Patterns:[0:{Pattern:\"hhb\",Color:15},1:{Pattern:\"flo\",Color:0},2:{Pattern:\"sku\",Color:14},3:{Pattern:\"mc\",Color:14},4:{Pattern:\"ms\",Color:14},5:{Pattern:\"tt\",Color:14}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"flo\",Color:2},1:{Pattern:\"bri\",Color:7},2:{Pattern:\"bo\",Color:12},3:{Pattern:\"tts\",Color:12},4:{Pattern:\"bt\",Color:0},5:{Pattern:\"bs\",Color:2}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[0:{Pattern:\"tts\",Color:8},1:{Pattern:\"bs\",Color:14},2:{Pattern:\"ls\",Color:3},3:{Pattern:\"rs\",Color:3},4:{Pattern:\"bo\",Color:3},5:{Pattern:\"dls\",Color:1}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 8 {BlockEntityTag:{Patterns:[0:{Pattern:\"cs\",Color:0},1:{Pattern:\"tts\",Color:8},2:{Pattern:\"flo\",Color:11},3:{Pattern:\"gru\",Color:0},4:{Pattern:\"flo\",Color:0},5:{Pattern:\"cre\",Color:0}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"dls\",Color:3},1:{Pattern:\"rd\",Color:0},2:{Pattern:\"hhb\",Color:7},3:{Pattern:\"cbo\",Color:0},4:{Pattern:\"bts\",Color:14}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"gra\",Color:1},1:{Pattern:\"gru\",Color:14},2:{Pattern:\"gru\",Color:11},3:{Pattern:\"gru\",Color:10},4:{Pattern:\"gru\",Color:12}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[{Color:0,Pattern:\"sc\"},{Color:0,Pattern:\"cs\"},{Color:15,Pattern:\"bo\"},{Color:0,Pattern:\"tt\"},{Color:15,Pattern:\"cbo\"},{Color:0,Pattern:\"bt\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[0:{Pattern:\"tt\",Color:0},1:{Pattern:\"mr\",Color:0},2:{Pattern:\"hhb\",Color:15},3:{Pattern:\"cs\",Color:0},4:{Pattern:\"cbo\",Color:15},5:{Pattern:\"bt\",Color:0}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[{Color:0,Pattern:\"mr\"},{Color:15,Pattern:\"tr\"},{Color:0,Pattern:\"bt\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[{Color:4,Pattern:\"hh\"},{Color:15,Pattern:\"ss\"},{Color:11,Pattern:\"sc\"},{Color:1,Pattern:\"hhb\"},{Color:9,Pattern:\"br\"},{Color:11,Pattern:\"bo\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 12 {BlockEntityTag:{Patterns:[{Color:15,Pattern:\"mc\"},{Color:0,Pattern:\"sku\"},{Color:10,Pattern:\"ms\"},{Color:10,Pattern:\"ms\"},{Color:10,Pattern:\"hhb\"},{Color:3,Pattern:\"bts\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[{Color:11,Pattern:\"sc\"},{Color:11,Pattern:\"ts\"},{Color:11,Pattern:\"hhb\"},{Color:0,Pattern:\"moj\"},{Color:11,Pattern:\"ms\"},{Color:11,Pattern:\"tt\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[{Color:1,Pattern:\"mr\"},{Color:15,Pattern:\"bs\"},{Color:7,Pattern:\"cs\"},{Color:15,Pattern:\"bo\"},{Color:0,Pattern:\"ms\"},{Color:15,Pattern:\"hh\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 12 {BlockEntityTag:{Patterns:[{Color:2,Pattern:\"cbo\"},{Color:2,Pattern:\"moj\"},{Color:2,Pattern:\"mr\"},{Color:0,Pattern:\"ld\"},{Color:11,Pattern:\"tl\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[{Color:15,Pattern:\"mc\"},{Color:11,Pattern:\"lud\"},{Color:11,Pattern:\"ld\"},{Color:0,Pattern:\"tl\"},{Color:11,Pattern:\"ls\"},{Color:11,Pattern:\"tts\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[{Color:1,Pattern:\"sku\"},{Color:2,Pattern:\"flo\"},{Color:11,Pattern:\"moj\"},{Color:11,Pattern:\"mc\"},{Color:0,Pattern:\"hhb\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[{Color:1,Pattern:\"tts\"},{Color:15,Pattern:\"ls\"},{Color:15,Pattern:\"rs\"},{Color:1,Pattern:\"sc\"},{Color:0,Pattern:\"lud\"},{Color:0,Pattern:\"rd\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[{Color:0,Pattern:\"mr\"},{Color:0,Pattern:\"bts\"},{Color:7,Pattern:\"sku\"},{Color:15,Pattern:\"mc\"},{Color:0,Pattern:\"bo\"},{Color:0,Pattern:\"tt\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 15 {BlockEntityTag:{Patterns:[{Color:4,Pattern:\"mc\"},{Color:15,Pattern:\"ss\"},{Color:15,Pattern:\"cr\"},{Color:1,Pattern:\"bt\"},{Color:15,Pattern:\"sku\"},{Color:15,Pattern:\"bs\"}]}}"));
        list.add(ItemStackUtil.stringtostack("banner 1 0 {BlockEntityTag:{Patterns:[{Color:11,Pattern:\"cbo\"},{Color:11,Pattern:\"tt\"},{Color:11,Pattern:\"hhb\"},{Color:11,Pattern:\"ts\"},{Color:0,Pattern:\"bt\"},{Color:11,Pattern:\"bs\"}]}}"));
        final StringBuilder sb = new StringBuilder();
        while (0 <= 15000) {
            sb.append("\\ufdfd");
            int n = 0;
            ++n;
        }
        removeSuspiciousTags(list);
    }
    
    public static void removeSuspiciousTags(final List list) {
        for (final ItemStack itemStack : list) {
            if (itemStack.hasTagCompound()) {
                itemStack.getTagCompound().setBoolean("Zaszlok", true);
            }
        }
    }
    
    @Override
    public ItemStack getIconItemStack() {
        return ItemStackUtil.stringtostack("minecraft:banner 1 0 {BlockEntityTag:{Patterns:[0:{Pattern:\"moj\",Color:15},1:{Pattern:\"flo\",Color:0},2:{Pattern:\"gru\",Color:5},3:{Pattern:\"mc\",Color:15},4:{Pattern:\"bt\",Color:7},5:{Pattern:\"bts\",Color:0}],Base:0}}");
    }
    
    @Override
    public String getTranslatedTabLabel() {
        return "§cZ\u00e1szl\u00f3k";
    }
    
    @Override
    public boolean hasSearchBar() {
        return true;
    }
}
