package com.viaversion.viaversion.protocols.protocol1_12to1_11_1;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ClientboundPackets1_12 implements ClientboundPacketType
{
    SPAWN_ENTITY("SPAWN_ENTITY", 0), 
    SPAWN_EXPERIENCE_ORB("SPAWN_EXPERIENCE_ORB", 1), 
    SPAWN_GLOBAL_ENTITY("SPAWN_GLOBAL_ENTITY", 2), 
    SPAWN_MOB("SPAWN_MOB", 3), 
    SPAWN_PAINTING("SPAWN_PAINTING", 4), 
    SPAWN_PLAYER("SPAWN_PLAYER", 5), 
    ENTITY_ANIMATION("ENTITY_ANIMATION", 6), 
    STATISTICS("STATISTICS", 7), 
    BLOCK_BREAK_ANIMATION("BLOCK_BREAK_ANIMATION", 8), 
    BLOCK_ENTITY_DATA("BLOCK_ENTITY_DATA", 9), 
    BLOCK_ACTION("BLOCK_ACTION", 10), 
    BLOCK_CHANGE("BLOCK_CHANGE", 11), 
    BOSSBAR("BOSSBAR", 12), 
    SERVER_DIFFICULTY("SERVER_DIFFICULTY", 13), 
    TAB_COMPLETE("TAB_COMPLETE", 14), 
    CHAT_MESSAGE("CHAT_MESSAGE", 15), 
    MULTI_BLOCK_CHANGE("MULTI_BLOCK_CHANGE", 16), 
    WINDOW_CONFIRMATION("WINDOW_CONFIRMATION", 17), 
    CLOSE_WINDOW("CLOSE_WINDOW", 18), 
    OPEN_WINDOW("OPEN_WINDOW", 19), 
    WINDOW_ITEMS("WINDOW_ITEMS", 20), 
    WINDOW_PROPERTY("WINDOW_PROPERTY", 21), 
    SET_SLOT("SET_SLOT", 22), 
    COOLDOWN("COOLDOWN", 23), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 24), 
    NAMED_SOUND("NAMED_SOUND", 25), 
    DISCONNECT("DISCONNECT", 26), 
    ENTITY_STATUS("ENTITY_STATUS", 27), 
    EXPLOSION("EXPLOSION", 28), 
    UNLOAD_CHUNK("UNLOAD_CHUNK", 29), 
    GAME_EVENT("GAME_EVENT", 30), 
    KEEP_ALIVE("KEEP_ALIVE", 31), 
    CHUNK_DATA("CHUNK_DATA", 32), 
    EFFECT("EFFECT", 33), 
    SPAWN_PARTICLE("SPAWN_PARTICLE", 34), 
    JOIN_GAME("JOIN_GAME", 35), 
    MAP_DATA("MAP_DATA", 36), 
    ENTITY_MOVEMENT("ENTITY_MOVEMENT", 37), 
    ENTITY_POSITION("ENTITY_POSITION", 38), 
    ENTITY_POSITION_AND_ROTATION("ENTITY_POSITION_AND_ROTATION", 39), 
    ENTITY_ROTATION("ENTITY_ROTATION", 40), 
    VEHICLE_MOVE("VEHICLE_MOVE", 41), 
    OPEN_SIGN_EDITOR("OPEN_SIGN_EDITOR", 42), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 43), 
    COMBAT_EVENT("COMBAT_EVENT", 44), 
    PLAYER_INFO("PLAYER_INFO", 45), 
    PLAYER_POSITION("PLAYER_POSITION", 46), 
    USE_BED("USE_BED", 47), 
    UNLOCK_RECIPES("UNLOCK_RECIPES", 48), 
    DESTROY_ENTITIES("DESTROY_ENTITIES", 49), 
    REMOVE_ENTITY_EFFECT("REMOVE_ENTITY_EFFECT", 50), 
    RESOURCE_PACK("RESOURCE_PACK", 51), 
    RESPAWN("RESPAWN", 52), 
    ENTITY_HEAD_LOOK("ENTITY_HEAD_LOOK", 53), 
    SELECT_ADVANCEMENTS_TAB("SELECT_ADVANCEMENTS_TAB", 54), 
    WORLD_BORDER("WORLD_BORDER", 55), 
    CAMERA("CAMERA", 56), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 57), 
    DISPLAY_SCOREBOARD("DISPLAY_SCOREBOARD", 58), 
    ENTITY_METADATA("ENTITY_METADATA", 59), 
    ATTACH_ENTITY("ATTACH_ENTITY", 60), 
    ENTITY_VELOCITY("ENTITY_VELOCITY", 61), 
    ENTITY_EQUIPMENT("ENTITY_EQUIPMENT", 62), 
    SET_EXPERIENCE("SET_EXPERIENCE", 63), 
    UPDATE_HEALTH("UPDATE_HEALTH", 64), 
    SCOREBOARD_OBJECTIVE("SCOREBOARD_OBJECTIVE", 65), 
    SET_PASSENGERS("SET_PASSENGERS", 66), 
    TEAMS("TEAMS", 67), 
    UPDATE_SCORE("UPDATE_SCORE", 68), 
    SPAWN_POSITION("SPAWN_POSITION", 69), 
    TIME_UPDATE("TIME_UPDATE", 70), 
    TITLE("TITLE", 71), 
    SOUND("SOUND", 72), 
    TAB_LIST("TAB_LIST", 73), 
    COLLECT_ITEM("COLLECT_ITEM", 74), 
    ENTITY_TELEPORT("ENTITY_TELEPORT", 75), 
    ADVANCEMENTS("ADVANCEMENTS", 76), 
    ENTITY_PROPERTIES("ENTITY_PROPERTIES", 77), 
    ENTITY_EFFECT("ENTITY_EFFECT", 78);
    
    private static final ClientboundPackets1_12[] $VALUES;
    
    private ClientboundPackets1_12(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ClientboundPackets1_12[] { ClientboundPackets1_12.SPAWN_ENTITY, ClientboundPackets1_12.SPAWN_EXPERIENCE_ORB, ClientboundPackets1_12.SPAWN_GLOBAL_ENTITY, ClientboundPackets1_12.SPAWN_MOB, ClientboundPackets1_12.SPAWN_PAINTING, ClientboundPackets1_12.SPAWN_PLAYER, ClientboundPackets1_12.ENTITY_ANIMATION, ClientboundPackets1_12.STATISTICS, ClientboundPackets1_12.BLOCK_BREAK_ANIMATION, ClientboundPackets1_12.BLOCK_ENTITY_DATA, ClientboundPackets1_12.BLOCK_ACTION, ClientboundPackets1_12.BLOCK_CHANGE, ClientboundPackets1_12.BOSSBAR, ClientboundPackets1_12.SERVER_DIFFICULTY, ClientboundPackets1_12.TAB_COMPLETE, ClientboundPackets1_12.CHAT_MESSAGE, ClientboundPackets1_12.MULTI_BLOCK_CHANGE, ClientboundPackets1_12.WINDOW_CONFIRMATION, ClientboundPackets1_12.CLOSE_WINDOW, ClientboundPackets1_12.OPEN_WINDOW, ClientboundPackets1_12.WINDOW_ITEMS, ClientboundPackets1_12.WINDOW_PROPERTY, ClientboundPackets1_12.SET_SLOT, ClientboundPackets1_12.COOLDOWN, ClientboundPackets1_12.PLUGIN_MESSAGE, ClientboundPackets1_12.NAMED_SOUND, ClientboundPackets1_12.DISCONNECT, ClientboundPackets1_12.ENTITY_STATUS, ClientboundPackets1_12.EXPLOSION, ClientboundPackets1_12.UNLOAD_CHUNK, ClientboundPackets1_12.GAME_EVENT, ClientboundPackets1_12.KEEP_ALIVE, ClientboundPackets1_12.CHUNK_DATA, ClientboundPackets1_12.EFFECT, ClientboundPackets1_12.SPAWN_PARTICLE, ClientboundPackets1_12.JOIN_GAME, ClientboundPackets1_12.MAP_DATA, ClientboundPackets1_12.ENTITY_MOVEMENT, ClientboundPackets1_12.ENTITY_POSITION, ClientboundPackets1_12.ENTITY_POSITION_AND_ROTATION, ClientboundPackets1_12.ENTITY_ROTATION, ClientboundPackets1_12.VEHICLE_MOVE, ClientboundPackets1_12.OPEN_SIGN_EDITOR, ClientboundPackets1_12.PLAYER_ABILITIES, ClientboundPackets1_12.COMBAT_EVENT, ClientboundPackets1_12.PLAYER_INFO, ClientboundPackets1_12.PLAYER_POSITION, ClientboundPackets1_12.USE_BED, ClientboundPackets1_12.UNLOCK_RECIPES, ClientboundPackets1_12.DESTROY_ENTITIES, ClientboundPackets1_12.REMOVE_ENTITY_EFFECT, ClientboundPackets1_12.RESOURCE_PACK, ClientboundPackets1_12.RESPAWN, ClientboundPackets1_12.ENTITY_HEAD_LOOK, ClientboundPackets1_12.SELECT_ADVANCEMENTS_TAB, ClientboundPackets1_12.WORLD_BORDER, ClientboundPackets1_12.CAMERA, ClientboundPackets1_12.HELD_ITEM_CHANGE, ClientboundPackets1_12.DISPLAY_SCOREBOARD, ClientboundPackets1_12.ENTITY_METADATA, ClientboundPackets1_12.ATTACH_ENTITY, ClientboundPackets1_12.ENTITY_VELOCITY, ClientboundPackets1_12.ENTITY_EQUIPMENT, ClientboundPackets1_12.SET_EXPERIENCE, ClientboundPackets1_12.UPDATE_HEALTH, ClientboundPackets1_12.SCOREBOARD_OBJECTIVE, ClientboundPackets1_12.SET_PASSENGERS, ClientboundPackets1_12.TEAMS, ClientboundPackets1_12.UPDATE_SCORE, ClientboundPackets1_12.SPAWN_POSITION, ClientboundPackets1_12.TIME_UPDATE, ClientboundPackets1_12.TITLE, ClientboundPackets1_12.SOUND, ClientboundPackets1_12.TAB_LIST, ClientboundPackets1_12.COLLECT_ITEM, ClientboundPackets1_12.ENTITY_TELEPORT, ClientboundPackets1_12.ADVANCEMENTS, ClientboundPackets1_12.ENTITY_PROPERTIES, ClientboundPackets1_12.ENTITY_EFFECT };
    }
}
