package com.viaversion.viaversion.protocols.protocol1_17to1_16_4;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ServerboundPackets1_17 implements ServerboundPacketType
{
    TELEPORT_CONFIRM("TELEPORT_CONFIRM", 0), 
    QUERY_BLOCK_NBT("QUERY_BLOCK_NBT", 1), 
    SET_DIFFICULTY("SET_DIFFICULTY", 2), 
    CHAT_MESSAGE("CHAT_MESSAGE", 3), 
    CLIENT_STATUS("CLIENT_STATUS", 4), 
    CLIENT_SETTINGS("CLIENT_SETTINGS", 5), 
    TAB_COMPLETE("TAB_COMPLETE", 6), 
    CLICK_WINDOW_BUTTON("CLICK_WINDOW_BUTTON", 7), 
    CLICK_WINDOW("CLICK_WINDOW", 8), 
    CLOSE_WINDOW("CLOSE_WINDOW", 9), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 10), 
    EDIT_BOOK("EDIT_BOOK", 11), 
    ENTITY_NBT_REQUEST("ENTITY_NBT_REQUEST", 12), 
    INTERACT_ENTITY("INTERACT_ENTITY", 13), 
    GENERATE_JIGSAW("GENERATE_JIGSAW", 14), 
    KEEP_ALIVE("KEEP_ALIVE", 15), 
    LOCK_DIFFICULTY("LOCK_DIFFICULTY", 16), 
    PLAYER_POSITION("PLAYER_POSITION", 17), 
    PLAYER_POSITION_AND_ROTATION("PLAYER_POSITION_AND_ROTATION", 18), 
    PLAYER_ROTATION("PLAYER_ROTATION", 19), 
    PLAYER_MOVEMENT("PLAYER_MOVEMENT", 20), 
    VEHICLE_MOVE("VEHICLE_MOVE", 21), 
    STEER_BOAT("STEER_BOAT", 22), 
    PICK_ITEM("PICK_ITEM", 23), 
    CRAFT_RECIPE_REQUEST("CRAFT_RECIPE_REQUEST", 24), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 25), 
    PLAYER_DIGGING("PLAYER_DIGGING", 26), 
    ENTITY_ACTION("ENTITY_ACTION", 27), 
    STEER_VEHICLE("STEER_VEHICLE", 28), 
    PONG("PONG", 29), 
    RECIPE_BOOK_DATA("RECIPE_BOOK_DATA", 30), 
    SEEN_RECIPE("SEEN_RECIPE", 31), 
    RENAME_ITEM("RENAME_ITEM", 32), 
    RESOURCE_PACK_STATUS("RESOURCE_PACK_STATUS", 33), 
    ADVANCEMENT_TAB("ADVANCEMENT_TAB", 34), 
    SELECT_TRADE("SELECT_TRADE", 35), 
    SET_BEACON_EFFECT("SET_BEACON_EFFECT", 36), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 37), 
    UPDATE_COMMAND_BLOCK("UPDATE_COMMAND_BLOCK", 38), 
    UPDATE_COMMAND_BLOCK_MINECART("UPDATE_COMMAND_BLOCK_MINECART", 39), 
    CREATIVE_INVENTORY_ACTION("CREATIVE_INVENTORY_ACTION", 40), 
    UPDATE_JIGSAW_BLOCK("UPDATE_JIGSAW_BLOCK", 41), 
    UPDATE_STRUCTURE_BLOCK("UPDATE_STRUCTURE_BLOCK", 42), 
    UPDATE_SIGN("UPDATE_SIGN", 43), 
    ANIMATION("ANIMATION", 44), 
    SPECTATE("SPECTATE", 45), 
    PLAYER_BLOCK_PLACEMENT("PLAYER_BLOCK_PLACEMENT", 46), 
    USE_ITEM("USE_ITEM", 47);
    
    private static final ServerboundPackets1_17[] $VALUES;
    
    private ServerboundPackets1_17(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ServerboundPackets1_17[] { ServerboundPackets1_17.TELEPORT_CONFIRM, ServerboundPackets1_17.QUERY_BLOCK_NBT, ServerboundPackets1_17.SET_DIFFICULTY, ServerboundPackets1_17.CHAT_MESSAGE, ServerboundPackets1_17.CLIENT_STATUS, ServerboundPackets1_17.CLIENT_SETTINGS, ServerboundPackets1_17.TAB_COMPLETE, ServerboundPackets1_17.CLICK_WINDOW_BUTTON, ServerboundPackets1_17.CLICK_WINDOW, ServerboundPackets1_17.CLOSE_WINDOW, ServerboundPackets1_17.PLUGIN_MESSAGE, ServerboundPackets1_17.EDIT_BOOK, ServerboundPackets1_17.ENTITY_NBT_REQUEST, ServerboundPackets1_17.INTERACT_ENTITY, ServerboundPackets1_17.GENERATE_JIGSAW, ServerboundPackets1_17.KEEP_ALIVE, ServerboundPackets1_17.LOCK_DIFFICULTY, ServerboundPackets1_17.PLAYER_POSITION, ServerboundPackets1_17.PLAYER_POSITION_AND_ROTATION, ServerboundPackets1_17.PLAYER_ROTATION, ServerboundPackets1_17.PLAYER_MOVEMENT, ServerboundPackets1_17.VEHICLE_MOVE, ServerboundPackets1_17.STEER_BOAT, ServerboundPackets1_17.PICK_ITEM, ServerboundPackets1_17.CRAFT_RECIPE_REQUEST, ServerboundPackets1_17.PLAYER_ABILITIES, ServerboundPackets1_17.PLAYER_DIGGING, ServerboundPackets1_17.ENTITY_ACTION, ServerboundPackets1_17.STEER_VEHICLE, ServerboundPackets1_17.PONG, ServerboundPackets1_17.RECIPE_BOOK_DATA, ServerboundPackets1_17.SEEN_RECIPE, ServerboundPackets1_17.RENAME_ITEM, ServerboundPackets1_17.RESOURCE_PACK_STATUS, ServerboundPackets1_17.ADVANCEMENT_TAB, ServerboundPackets1_17.SELECT_TRADE, ServerboundPackets1_17.SET_BEACON_EFFECT, ServerboundPackets1_17.HELD_ITEM_CHANGE, ServerboundPackets1_17.UPDATE_COMMAND_BLOCK, ServerboundPackets1_17.UPDATE_COMMAND_BLOCK_MINECART, ServerboundPackets1_17.CREATIVE_INVENTORY_ACTION, ServerboundPackets1_17.UPDATE_JIGSAW_BLOCK, ServerboundPackets1_17.UPDATE_STRUCTURE_BLOCK, ServerboundPackets1_17.UPDATE_SIGN, ServerboundPackets1_17.ANIMATION, ServerboundPackets1_17.SPECTATE, ServerboundPackets1_17.PLAYER_BLOCK_PLACEMENT, ServerboundPackets1_17.USE_ITEM };
    }
}
