package com.viaversion.viaversion.protocols.protocol1_13to1_12_2;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ClientboundPackets1_13 implements ClientboundPacketType
{
    SPAWN_ENTITY("SPAWN_ENTITY", 0), 
    SPAWN_EXPERIENCE_ORB("SPAWN_EXPERIENCE_ORB", 1), 
    SPAWN_GLOBAL_ENTITY("SPAWN_GLOBAL_ENTITY", 2), 
    SPAWN_MOB("SPAWN_MOB", 3), 
    SPAWN_PAINTING("SPAWN_PAINTING", 4), 
    SPAWN_PLAYER("SPAWN_PLAYER", 5), 
    ENTITY_ANIMATION("ENTITY_ANIMATION", 6), 
    STATISTICS("STATISTICS", 7), 
    BLOCK_BREAK_ANIMATION("BLOCK_BREAK_ANIMATION", 8), 
    BLOCK_ENTITY_DATA("BLOCK_ENTITY_DATA", 9), 
    BLOCK_ACTION("BLOCK_ACTION", 10), 
    BLOCK_CHANGE("BLOCK_CHANGE", 11), 
    BOSSBAR("BOSSBAR", 12), 
    SERVER_DIFFICULTY("SERVER_DIFFICULTY", 13), 
    CHAT_MESSAGE("CHAT_MESSAGE", 14), 
    MULTI_BLOCK_CHANGE("MULTI_BLOCK_CHANGE", 15), 
    TAB_COMPLETE("TAB_COMPLETE", 16), 
    DECLARE_COMMANDS("DECLARE_COMMANDS", 17), 
    WINDOW_CONFIRMATION("WINDOW_CONFIRMATION", 18), 
    CLOSE_WINDOW("CLOSE_WINDOW", 19), 
    OPEN_WINDOW("OPEN_WINDOW", 20), 
    WINDOW_ITEMS("WINDOW_ITEMS", 21), 
    WINDOW_PROPERTY("WINDOW_PROPERTY", 22), 
    SET_SLOT("SET_SLOT", 23), 
    COOLDOWN("COOLDOWN", 24), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 25), 
    NAMED_SOUND("NAMED_SOUND", 26), 
    DISCONNECT("DISCONNECT", 27), 
    ENTITY_STATUS("ENTITY_STATUS", 28), 
    NBT_QUERY("NBT_QUERY", 29), 
    EXPLOSION("EXPLOSION", 30), 
    UNLOAD_CHUNK("UNLOAD_CHUNK", 31), 
    GAME_EVENT("GAME_EVENT", 32), 
    KEEP_ALIVE("KEEP_ALIVE", 33), 
    CHUNK_DATA("CHUNK_DATA", 34), 
    EFFECT("EFFECT", 35), 
    SPAWN_PARTICLE("SPAWN_PARTICLE", 36), 
    JOIN_GAME("JOIN_GAME", 37), 
    MAP_DATA("MAP_DATA", 38), 
    ENTITY_MOVEMENT("ENTITY_MOVEMENT", 39), 
    ENTITY_POSITION("ENTITY_POSITION", 40), 
    ENTITY_POSITION_AND_ROTATION("ENTITY_POSITION_AND_ROTATION", 41), 
    ENTITY_ROTATION("ENTITY_ROTATION", 42), 
    VEHICLE_MOVE("VEHICLE_MOVE", 43), 
    OPEN_SIGN_EDITOR("OPEN_SIGN_EDITOR", 44), 
    CRAFT_RECIPE_RESPONSE("CRAFT_RECIPE_RESPONSE", 45), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 46), 
    COMBAT_EVENT("COMBAT_EVENT", 47), 
    PLAYER_INFO("PLAYER_INFO", 48), 
    FACE_PLAYER("FACE_PLAYER", 49), 
    PLAYER_POSITION("PLAYER_POSITION", 50), 
    USE_BED("USE_BED", 51), 
    UNLOCK_RECIPES("UNLOCK_RECIPES", 52), 
    DESTROY_ENTITIES("DESTROY_ENTITIES", 53), 
    REMOVE_ENTITY_EFFECT("REMOVE_ENTITY_EFFECT", 54), 
    RESOURCE_PACK("RESOURCE_PACK", 55), 
    RESPAWN("RESPAWN", 56), 
    ENTITY_HEAD_LOOK("ENTITY_HEAD_LOOK", 57), 
    SELECT_ADVANCEMENTS_TAB("SELECT_ADVANCEMENTS_TAB", 58), 
    WORLD_BORDER("WORLD_BORDER", 59), 
    CAMERA("CAMERA", 60), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 61), 
    DISPLAY_SCOREBOARD("DISPLAY_SCOREBOARD", 62), 
    ENTITY_METADATA("ENTITY_METADATA", 63), 
    ATTACH_ENTITY("ATTACH_ENTITY", 64), 
    ENTITY_VELOCITY("ENTITY_VELOCITY", 65), 
    ENTITY_EQUIPMENT("ENTITY_EQUIPMENT", 66), 
    SET_EXPERIENCE("SET_EXPERIENCE", 67), 
    UPDATE_HEALTH("UPDATE_HEALTH", 68), 
    SCOREBOARD_OBJECTIVE("SCOREBOARD_OBJECTIVE", 69), 
    SET_PASSENGERS("SET_PASSENGERS", 70), 
    TEAMS("TEAMS", 71), 
    UPDATE_SCORE("UPDATE_SCORE", 72), 
    SPAWN_POSITION("SPAWN_POSITION", 73), 
    TIME_UPDATE("TIME_UPDATE", 74), 
    TITLE("TITLE", 75), 
    STOP_SOUND("STOP_SOUND", 76), 
    SOUND("SOUND", 77), 
    TAB_LIST("TAB_LIST", 78), 
    COLLECT_ITEM("COLLECT_ITEM", 79), 
    ENTITY_TELEPORT("ENTITY_TELEPORT", 80), 
    ADVANCEMENTS("ADVANCEMENTS", 81), 
    ENTITY_PROPERTIES("ENTITY_PROPERTIES", 82), 
    ENTITY_EFFECT("ENTITY_EFFECT", 83), 
    DECLARE_RECIPES("DECLARE_RECIPES", 84), 
    TAGS("TAGS", 85);
    
    private static final ClientboundPackets1_13[] $VALUES;
    
    private ClientboundPackets1_13(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ClientboundPackets1_13[] { ClientboundPackets1_13.SPAWN_ENTITY, ClientboundPackets1_13.SPAWN_EXPERIENCE_ORB, ClientboundPackets1_13.SPAWN_GLOBAL_ENTITY, ClientboundPackets1_13.SPAWN_MOB, ClientboundPackets1_13.SPAWN_PAINTING, ClientboundPackets1_13.SPAWN_PLAYER, ClientboundPackets1_13.ENTITY_ANIMATION, ClientboundPackets1_13.STATISTICS, ClientboundPackets1_13.BLOCK_BREAK_ANIMATION, ClientboundPackets1_13.BLOCK_ENTITY_DATA, ClientboundPackets1_13.BLOCK_ACTION, ClientboundPackets1_13.BLOCK_CHANGE, ClientboundPackets1_13.BOSSBAR, ClientboundPackets1_13.SERVER_DIFFICULTY, ClientboundPackets1_13.CHAT_MESSAGE, ClientboundPackets1_13.MULTI_BLOCK_CHANGE, ClientboundPackets1_13.TAB_COMPLETE, ClientboundPackets1_13.DECLARE_COMMANDS, ClientboundPackets1_13.WINDOW_CONFIRMATION, ClientboundPackets1_13.CLOSE_WINDOW, ClientboundPackets1_13.OPEN_WINDOW, ClientboundPackets1_13.WINDOW_ITEMS, ClientboundPackets1_13.WINDOW_PROPERTY, ClientboundPackets1_13.SET_SLOT, ClientboundPackets1_13.COOLDOWN, ClientboundPackets1_13.PLUGIN_MESSAGE, ClientboundPackets1_13.NAMED_SOUND, ClientboundPackets1_13.DISCONNECT, ClientboundPackets1_13.ENTITY_STATUS, ClientboundPackets1_13.NBT_QUERY, ClientboundPackets1_13.EXPLOSION, ClientboundPackets1_13.UNLOAD_CHUNK, ClientboundPackets1_13.GAME_EVENT, ClientboundPackets1_13.KEEP_ALIVE, ClientboundPackets1_13.CHUNK_DATA, ClientboundPackets1_13.EFFECT, ClientboundPackets1_13.SPAWN_PARTICLE, ClientboundPackets1_13.JOIN_GAME, ClientboundPackets1_13.MAP_DATA, ClientboundPackets1_13.ENTITY_MOVEMENT, ClientboundPackets1_13.ENTITY_POSITION, ClientboundPackets1_13.ENTITY_POSITION_AND_ROTATION, ClientboundPackets1_13.ENTITY_ROTATION, ClientboundPackets1_13.VEHICLE_MOVE, ClientboundPackets1_13.OPEN_SIGN_EDITOR, ClientboundPackets1_13.CRAFT_RECIPE_RESPONSE, ClientboundPackets1_13.PLAYER_ABILITIES, ClientboundPackets1_13.COMBAT_EVENT, ClientboundPackets1_13.PLAYER_INFO, ClientboundPackets1_13.FACE_PLAYER, ClientboundPackets1_13.PLAYER_POSITION, ClientboundPackets1_13.USE_BED, ClientboundPackets1_13.UNLOCK_RECIPES, ClientboundPackets1_13.DESTROY_ENTITIES, ClientboundPackets1_13.REMOVE_ENTITY_EFFECT, ClientboundPackets1_13.RESOURCE_PACK, ClientboundPackets1_13.RESPAWN, ClientboundPackets1_13.ENTITY_HEAD_LOOK, ClientboundPackets1_13.SELECT_ADVANCEMENTS_TAB, ClientboundPackets1_13.WORLD_BORDER, ClientboundPackets1_13.CAMERA, ClientboundPackets1_13.HELD_ITEM_CHANGE, ClientboundPackets1_13.DISPLAY_SCOREBOARD, ClientboundPackets1_13.ENTITY_METADATA, ClientboundPackets1_13.ATTACH_ENTITY, ClientboundPackets1_13.ENTITY_VELOCITY, ClientboundPackets1_13.ENTITY_EQUIPMENT, ClientboundPackets1_13.SET_EXPERIENCE, ClientboundPackets1_13.UPDATE_HEALTH, ClientboundPackets1_13.SCOREBOARD_OBJECTIVE, ClientboundPackets1_13.SET_PASSENGERS, ClientboundPackets1_13.TEAMS, ClientboundPackets1_13.UPDATE_SCORE, ClientboundPackets1_13.SPAWN_POSITION, ClientboundPackets1_13.TIME_UPDATE, ClientboundPackets1_13.TITLE, ClientboundPackets1_13.STOP_SOUND, ClientboundPackets1_13.SOUND, ClientboundPackets1_13.TAB_LIST, ClientboundPackets1_13.COLLECT_ITEM, ClientboundPackets1_13.ENTITY_TELEPORT, ClientboundPackets1_13.ADVANCEMENTS, ClientboundPackets1_13.ENTITY_PROPERTIES, ClientboundPackets1_13.ENTITY_EFFECT, ClientboundPackets1_13.DECLARE_RECIPES, ClientboundPackets1_13.TAGS };
    }
}
