package com.viaversion.viaversion.protocols.protocol1_18to1_17_1;

import com.viaversion.viaversion.api.protocol.packet.*;

public enum ClientboundPackets1_18 implements ClientboundPacketType
{
    SPAWN_ENTITY("SPAWN_ENTITY", 0), 
    SPAWN_EXPERIENCE_ORB("SPAWN_EXPERIENCE_ORB", 1), 
    SPAWN_MOB("SPAWN_MOB", 2), 
    SPAWN_PAINTING("SPAWN_PAINTING", 3), 
    SPAWN_PLAYER("SPAWN_PLAYER", 4), 
    ADD_VIBRATION_SIGNAL("ADD_VIBRATION_SIGNAL", 5), 
    ENTITY_ANIMATION("ENTITY_ANIMATION", 6), 
    STATISTICS("STATISTICS", 7), 
    ACKNOWLEDGE_PLAYER_DIGGING("ACKNOWLEDGE_PLAYER_DIGGING", 8), 
    BLOCK_BREAK_ANIMATION("BLOCK_BREAK_ANIMATION", 9), 
    BLOCK_ENTITY_DATA("BLOCK_ENTITY_DATA", 10), 
    BLOCK_ACTION("BLOCK_ACTION", 11), 
    BLOCK_CHANGE("BLOCK_CHANGE", 12), 
    BOSSBAR("BOSSBAR", 13), 
    SERVER_DIFFICULTY("SERVER_DIFFICULTY", 14), 
    CHAT_MESSAGE("CHAT_MESSAGE", 15), 
    CLEAR_TITLES("CLEAR_TITLES", 16), 
    TAB_COMPLETE("TAB_COMPLETE", 17), 
    DECLARE_COMMANDS("DECLARE_COMMANDS", 18), 
    CLOSE_WINDOW("CLOSE_WINDOW", 19), 
    WINDOW_ITEMS("WINDOW_ITEMS", 20), 
    WINDOW_PROPERTY("WINDOW_PROPERTY", 21), 
    SET_SLOT("SET_SLOT", 22), 
    COOLDOWN("COOLDOWN", 23), 
    PLUGIN_MESSAGE("PLUGIN_MESSAGE", 24), 
    NAMED_SOUND("NAMED_SOUND", 25), 
    DISCONNECT("DISCONNECT", 26), 
    ENTITY_STATUS("ENTITY_STATUS", 27), 
    EXPLOSION("EXPLOSION", 28), 
    UNLOAD_CHUNK("UNLOAD_CHUNK", 29), 
    GAME_EVENT("GAME_EVENT", 30), 
    OPEN_HORSE_WINDOW("OPEN_HORSE_WINDOW", 31), 
    WORLD_BORDER_INIT("WORLD_BORDER_INIT", 32), 
    KEEP_ALIVE("KEEP_ALIVE", 33), 
    CHUNK_DATA("CHUNK_DATA", 34), 
    EFFECT("EFFECT", 35), 
    SPAWN_PARTICLE("SPAWN_PARTICLE", 36), 
    UPDATE_LIGHT("UPDATE_LIGHT", 37), 
    JOIN_GAME("JOIN_GAME", 38), 
    MAP_DATA("MAP_DATA", 39), 
    TRADE_LIST("TRADE_LIST", 40), 
    ENTITY_POSITION("ENTITY_POSITION", 41), 
    ENTITY_POSITION_AND_ROTATION("ENTITY_POSITION_AND_ROTATION", 42), 
    ENTITY_ROTATION("ENTITY_ROTATION", 43), 
    VEHICLE_MOVE("VEHICLE_MOVE", 44), 
    OPEN_BOOK("OPEN_BOOK", 45), 
    OPEN_WINDOW("OPEN_WINDOW", 46), 
    OPEN_SIGN_EDITOR("OPEN_SIGN_EDITOR", 47), 
    PING("PING", 48), 
    CRAFT_RECIPE_RESPONSE("CRAFT_RECIPE_RESPONSE", 49), 
    PLAYER_ABILITIES("PLAYER_ABILITIES", 50), 
    COMBAT_END("COMBAT_END", 51), 
    COMBAT_ENTER("COMBAT_ENTER", 52), 
    COMBAT_KILL("COMBAT_KILL", 53), 
    PLAYER_INFO("PLAYER_INFO", 54), 
    FACE_PLAYER("FACE_PLAYER", 55), 
    PLAYER_POSITION("PLAYER_POSITION", 56), 
    UNLOCK_RECIPES("UNLOCK_RECIPES", 57), 
    REMOVE_ENTITIES("REMOVE_ENTITIES", 58), 
    REMOVE_ENTITY_EFFECT("REMOVE_ENTITY_EFFECT", 59), 
    RESOURCE_PACK("RESOURCE_PACK", 60), 
    RESPAWN("RESPAWN", 61), 
    ENTITY_HEAD_LOOK("ENTITY_HEAD_LOOK", 62), 
    MULTI_BLOCK_CHANGE("MULTI_BLOCK_CHANGE", 63), 
    SELECT_ADVANCEMENTS_TAB("SELECT_ADVANCEMENTS_TAB", 64), 
    ACTIONBAR("ACTIONBAR", 65), 
    WORLD_BORDER_CENTER("WORLD_BORDER_CENTER", 66), 
    WORLD_BORDER_LERP_SIZE("WORLD_BORDER_LERP_SIZE", 67), 
    WORLD_BORDER_SIZE("WORLD_BORDER_SIZE", 68), 
    WORLD_BORDER_WARNING_DELAY("WORLD_BORDER_WARNING_DELAY", 69), 
    WORLD_BORDER_WARNING_DISTANCE("WORLD_BORDER_WARNING_DISTANCE", 70), 
    CAMERA("CAMERA", 71), 
    HELD_ITEM_CHANGE("HELD_ITEM_CHANGE", 72), 
    UPDATE_VIEW_POSITION("UPDATE_VIEW_POSITION", 73), 
    UPDATE_VIEW_DISTANCE("UPDATE_VIEW_DISTANCE", 74), 
    SPAWN_POSITION("SPAWN_POSITION", 75), 
    DISPLAY_SCOREBOARD("DISPLAY_SCOREBOARD", 76), 
    ENTITY_METADATA("ENTITY_METADATA", 77), 
    ATTACH_ENTITY("ATTACH_ENTITY", 78), 
    ENTITY_VELOCITY("ENTITY_VELOCITY", 79), 
    ENTITY_EQUIPMENT("ENTITY_EQUIPMENT", 80), 
    SET_EXPERIENCE("SET_EXPERIENCE", 81), 
    UPDATE_HEALTH("UPDATE_HEALTH", 82), 
    SCOREBOARD_OBJECTIVE("SCOREBOARD_OBJECTIVE", 83), 
    SET_PASSENGERS("SET_PASSENGERS", 84), 
    TEAMS("TEAMS", 85), 
    UPDATE_SCORE("UPDATE_SCORE", 86), 
    SET_SIMULATION_DISTANCE("SET_SIMULATION_DISTANCE", 87), 
    TITLE_SUBTITLE("TITLE_SUBTITLE", 88), 
    TIME_UPDATE("TIME_UPDATE", 89), 
    TITLE_TEXT("TITLE_TEXT", 90), 
    TITLE_TIMES("TITLE_TIMES", 91), 
    ENTITY_SOUND("ENTITY_SOUND", 92), 
    SOUND("SOUND", 93), 
    STOP_SOUND("STOP_SOUND", 94), 
    TAB_LIST("TAB_LIST", 95), 
    NBT_QUERY("NBT_QUERY", 96), 
    COLLECT_ITEM("COLLECT_ITEM", 97), 
    ENTITY_TELEPORT("ENTITY_TELEPORT", 98), 
    ADVANCEMENTS("ADVANCEMENTS", 99), 
    ENTITY_PROPERTIES("ENTITY_PROPERTIES", 100), 
    ENTITY_EFFECT("ENTITY_EFFECT", 101), 
    DECLARE_RECIPES("DECLARE_RECIPES", 102), 
    TAGS("TAGS", 103);
    
    private static final ClientboundPackets1_18[] $VALUES;
    
    private ClientboundPackets1_18(final String s, final int n) {
    }
    
    @Override
    public int getId() {
        return this.ordinal();
    }
    
    @Override
    public String getName() {
        return this.name();
    }
    
    static {
        $VALUES = new ClientboundPackets1_18[] { ClientboundPackets1_18.SPAWN_ENTITY, ClientboundPackets1_18.SPAWN_EXPERIENCE_ORB, ClientboundPackets1_18.SPAWN_MOB, ClientboundPackets1_18.SPAWN_PAINTING, ClientboundPackets1_18.SPAWN_PLAYER, ClientboundPackets1_18.ADD_VIBRATION_SIGNAL, ClientboundPackets1_18.ENTITY_ANIMATION, ClientboundPackets1_18.STATISTICS, ClientboundPackets1_18.ACKNOWLEDGE_PLAYER_DIGGING, ClientboundPackets1_18.BLOCK_BREAK_ANIMATION, ClientboundPackets1_18.BLOCK_ENTITY_DATA, ClientboundPackets1_18.BLOCK_ACTION, ClientboundPackets1_18.BLOCK_CHANGE, ClientboundPackets1_18.BOSSBAR, ClientboundPackets1_18.SERVER_DIFFICULTY, ClientboundPackets1_18.CHAT_MESSAGE, ClientboundPackets1_18.CLEAR_TITLES, ClientboundPackets1_18.TAB_COMPLETE, ClientboundPackets1_18.DECLARE_COMMANDS, ClientboundPackets1_18.CLOSE_WINDOW, ClientboundPackets1_18.WINDOW_ITEMS, ClientboundPackets1_18.WINDOW_PROPERTY, ClientboundPackets1_18.SET_SLOT, ClientboundPackets1_18.COOLDOWN, ClientboundPackets1_18.PLUGIN_MESSAGE, ClientboundPackets1_18.NAMED_SOUND, ClientboundPackets1_18.DISCONNECT, ClientboundPackets1_18.ENTITY_STATUS, ClientboundPackets1_18.EXPLOSION, ClientboundPackets1_18.UNLOAD_CHUNK, ClientboundPackets1_18.GAME_EVENT, ClientboundPackets1_18.OPEN_HORSE_WINDOW, ClientboundPackets1_18.WORLD_BORDER_INIT, ClientboundPackets1_18.KEEP_ALIVE, ClientboundPackets1_18.CHUNK_DATA, ClientboundPackets1_18.EFFECT, ClientboundPackets1_18.SPAWN_PARTICLE, ClientboundPackets1_18.UPDATE_LIGHT, ClientboundPackets1_18.JOIN_GAME, ClientboundPackets1_18.MAP_DATA, ClientboundPackets1_18.TRADE_LIST, ClientboundPackets1_18.ENTITY_POSITION, ClientboundPackets1_18.ENTITY_POSITION_AND_ROTATION, ClientboundPackets1_18.ENTITY_ROTATION, ClientboundPackets1_18.VEHICLE_MOVE, ClientboundPackets1_18.OPEN_BOOK, ClientboundPackets1_18.OPEN_WINDOW, ClientboundPackets1_18.OPEN_SIGN_EDITOR, ClientboundPackets1_18.PING, ClientboundPackets1_18.CRAFT_RECIPE_RESPONSE, ClientboundPackets1_18.PLAYER_ABILITIES, ClientboundPackets1_18.COMBAT_END, ClientboundPackets1_18.COMBAT_ENTER, ClientboundPackets1_18.COMBAT_KILL, ClientboundPackets1_18.PLAYER_INFO, ClientboundPackets1_18.FACE_PLAYER, ClientboundPackets1_18.PLAYER_POSITION, ClientboundPackets1_18.UNLOCK_RECIPES, ClientboundPackets1_18.REMOVE_ENTITIES, ClientboundPackets1_18.REMOVE_ENTITY_EFFECT, ClientboundPackets1_18.RESOURCE_PACK, ClientboundPackets1_18.RESPAWN, ClientboundPackets1_18.ENTITY_HEAD_LOOK, ClientboundPackets1_18.MULTI_BLOCK_CHANGE, ClientboundPackets1_18.SELECT_ADVANCEMENTS_TAB, ClientboundPackets1_18.ACTIONBAR, ClientboundPackets1_18.WORLD_BORDER_CENTER, ClientboundPackets1_18.WORLD_BORDER_LERP_SIZE, ClientboundPackets1_18.WORLD_BORDER_SIZE, ClientboundPackets1_18.WORLD_BORDER_WARNING_DELAY, ClientboundPackets1_18.WORLD_BORDER_WARNING_DISTANCE, ClientboundPackets1_18.CAMERA, ClientboundPackets1_18.HELD_ITEM_CHANGE, ClientboundPackets1_18.UPDATE_VIEW_POSITION, ClientboundPackets1_18.UPDATE_VIEW_DISTANCE, ClientboundPackets1_18.SPAWN_POSITION, ClientboundPackets1_18.DISPLAY_SCOREBOARD, ClientboundPackets1_18.ENTITY_METADATA, ClientboundPackets1_18.ATTACH_ENTITY, ClientboundPackets1_18.ENTITY_VELOCITY, ClientboundPackets1_18.ENTITY_EQUIPMENT, ClientboundPackets1_18.SET_EXPERIENCE, ClientboundPackets1_18.UPDATE_HEALTH, ClientboundPackets1_18.SCOREBOARD_OBJECTIVE, ClientboundPackets1_18.SET_PASSENGERS, ClientboundPackets1_18.TEAMS, ClientboundPackets1_18.UPDATE_SCORE, ClientboundPackets1_18.SET_SIMULATION_DISTANCE, ClientboundPackets1_18.TITLE_SUBTITLE, ClientboundPackets1_18.TIME_UPDATE, ClientboundPackets1_18.TITLE_TEXT, ClientboundPackets1_18.TITLE_TIMES, ClientboundPackets1_18.ENTITY_SOUND, ClientboundPackets1_18.SOUND, ClientboundPackets1_18.STOP_SOUND, ClientboundPackets1_18.TAB_LIST, ClientboundPackets1_18.NBT_QUERY, ClientboundPackets1_18.COLLECT_ITEM, ClientboundPackets1_18.ENTITY_TELEPORT, ClientboundPackets1_18.ADVANCEMENTS, ClientboundPackets1_18.ENTITY_PROPERTIES, ClientboundPackets1_18.ENTITY_EFFECT, ClientboundPackets1_18.DECLARE_RECIPES, ClientboundPackets1_18.TAGS };
    }
}
